"use client";

import React, { useState } from "react";
import { HamediaLogo } from "@/components/ui/HamediaLogo";
import { 
  ArrowRight, 
  TrendingUp, 
  Sprout, 
  ShieldCheck, 
  Users, 
  Building,
  CheckCircle,
  Activity,
  Calculator,
  ChevronDown,
  Mail,
  Phone,
  HelpCircle,
  UtensilsCrossed,
  ArrowUpRight,
  BookOpen,
  Send,
  Layers,
  MapPin,
  ClipboardList,
  Flame,
  Award,
  Bot,
  Truck,
  Cpu,
  Home as HomeIcon,
  Wheat,
  Zap,
  Store
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import { useDesign, DesignVariant, StructureVariant } from "@/components/providers/DesignContext";
import { cn } from "@/lib/utils";

// FAQ type definition
interface FAQItem {
  question: string;
  answer: string;
}

export default function Home() {
  const { theme, structure } = useDesign();

  // --- SHARED STATE ---
  const [investmentAmount, setInvestmentAmount] = useState<number>(50000);
  const [selectedProfile, setSelectedProfile] = useState<"balanced" | "arghandab" | "solar" | "logistics">("balanced");
  const exchangeRate = 65; // AFN per USD

  // Calculations based on portfolio prospectus
  const getProfileData = () => {
    switch (selectedProfile) {
      case "arghandab":
        return {
          name: "Arghandab Flagship",
          yieldRate: 0.148,
          payback: 6.0,
          unitName: "Dairy Assets Funded",
          unitCost: 5500,
        };
      case "solar":
        return {
          name: "Solar Infrastructure",
          yieldRate: 0.125,
          payback: 7.0,
          unitName: "Solar Capacity Modules",
          unitCost: 8000,
        };
      case "logistics":
        return {
          name: "Cold-Chain Logistics",
          yieldRate: 0.162,
          payback: 5.0,
          unitName: "Cold Storage Nodes",
          unitCost: 6000,
        };
      case "balanced":
      default:
        return {
          name: "Balanced Growth",
          yieldRate: 0.155,
          payback: 5.5,
          unitName: "Diversified Venture Assets",
          unitCost: 5000,
        };
    }
  };

  const profile = getProfileData();
  const totalAnnualCashFlowUsd = Math.round(investmentAmount * profile.yieldRate);
  const fundedUnits = Math.round((investmentAmount / profile.unitCost) * 10) / 10;

  // Contact Form States
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    interest: "50k-100k",
    message: "",
  });

  const handleFormChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormSubmitted(true);
    toast.success("Thank you for your inquiry! Our investor relations representative will contact you shortly.");
  };

  // FAQ State
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const faqs: FAQItem[] = [
    {
      question: "Do I acquire equity in the business or ownership of the land?",
      answer: "No. The Economic Participation Model is structured so that investor capital goes directly to purchasing active operational inventory (such as livestock herd lines or energy components). You receive an Economic Participation Certificate giving you a contractual interest in the net benefits generated by that specific asset line. The land, physical facilities, and corporate entities remain 100% owned and controlled by the founders."
    },
    {
      question: "What is the minimum term of the investment and exit process?",
      answer: "The minimum intended term is 2.5 years to allow the project's assets to mature and stabilize. However, you can request divestment after 1 year. The company intends to accommodate divestment requests within 90 days, calculating your exit value based on your contractual interest in the current market value of the assets."
    },
    {
      question: "How are project assets tracked and reported?",
      answer: "We employ modern digital tracking technology. For livestock, every animal receives a digital RFID ear tag; for logistics and energy projects, smart flow meters and GPS trackers report directly to our cloud ledger. Investors receive regular operational summaries, yield logs, and are welcome to conduct site inspections."
    },
    {
      question: "How are direct operating costs accounted for?",
      answer: "Operating costs (such as feed, veterinary care, panel maintenance, or fuel) are charged directly to that specific project line. Net distributions are calculated after these direct costs are deducted from project revenue, ensuring investors do not subsidize unrelated general platform development."
    },
    {
      question: "What operational risks are involved?",
      answer: "Productive real-asset projects involve natural, biological, and market risks. Risk is shared proportionally. Because the investor holds a certificate interest in a specific asset line, both the company and the investor absorb outcomes matching that project's real performance."
    }
  ];

  // --- THEME-SPECIFIC DESIGN TOKENS ---
  interface ThemeStyles {
    bodyBg: string;
    textCharcoal: string;
    textGray: string;
    headingFont: string;
    sectionHeadingClass: string;
    subTitleClass: string;
    dividerClass: string;
    heroLeftBg: string;
    heroRightBg: string;
    heroTextClass: string;
    heroGridClass: string;
    accentText: string;
    primaryBtn: string;
    secondaryBtn: string;
    badgeClass: string;
    cardClass: string;
    iconContainer: string;
    checkIcon: string;
    calcCardBg: string;
    sliderAccent: string;
    calcStatBg: string;
    formBg: string;
    inputClass: string;
    formBtn: string;
    faqClass: string;
    slideLeftPanelBg: string;
    cardOverlay: string;
    cardBtnText: string;
  }

  const getThemeStyles = (): ThemeStyles => {
    return {
      bodyBg: "bg-[#092227]",
      textCharcoal: "text-white",
      textGray: "text-slate-300",
      headingFont: "font-sans font-black tracking-tight",
      sectionHeadingClass: "font-sans font-black tracking-tight text-[#10a5b2] uppercase",
      subTitleClass: "text-[#10a5b2]",
      dividerClass: "bg-[#10a5b2]",
      // Hero specific
      heroLeftBg: "bg-[#092227]",
      heroRightBg: "bg-[#092227]",
      heroTextClass: "font-sans font-black tracking-tight text-white uppercase",
      heroGridClass: "border border-white/5",
      accentText: "text-[#10a5b2]",
      primaryBtn: "bg-[#10a5b2] hover:bg-[#0c8a94] text-white font-bold rounded-xl shadow-lg hover:shadow-cyan-500/20 transition-all border-0",
      secondaryBtn: "border border-white/20 hover:border-[#10a5b2] text-white hover:text-[#10a5b2] bg-white/5 backdrop-blur-sm rounded-xl transition-all",
      badgeClass: "bg-[#10a5b2]/10 text-[#10a5b2] border border-[#10a5b2]/20 rounded-full",
      cardClass: "bg-[#0b2d34] border border-white/10 rounded-2xl shadow-lg hover:shadow-2xl hover:border-[#10a5b2]/30 transition-all duration-300",
      iconContainer: "bg-[#10a5b2]/15 text-[#10a5b2] border border-[#10a5b2]/20 rounded-xl",
      checkIcon: "text-[#10a5b2]",
      // Calculator specific
      calcCardBg: "bg-[#0b2d34] text-white rounded-2xl shadow-2xl border border-white/10",
      sliderAccent: "accent-[#10a5b2]",
      calcStatBg: "bg-white/5 border border-white/10 rounded-xl",
      // Form specific
      formBg: "bg-[#0b2d34] border border-white/10 text-white rounded-2xl p-8 shadow-2xl",
      inputClass: "bg-[#092227] border border-white/15 rounded-xl text-white placeholder:text-gray-400 focus:ring-2 focus:ring-[#10a5b2] focus:border-[#10a5b2]",
      formBtn: "bg-[#10a5b2] hover:bg-[#0c8a94] text-white font-bold rounded-xl shadow-lg transition-all",
      faqClass: "bg-[#0b2d34]/90 border border-white/10 rounded-xl text-white",
      slideLeftPanelBg: "bg-[#0b2d34] border border-white/10 rounded-xl text-white",
      cardOverlay: "bg-gradient-to-b from-[#0c4d57]/80 via-[#0a3a42]/90 to-[#072025]/98",
      cardBtnText: "text-[#0a3a42]"
    };
  };

  const t = getThemeStyles();

  // --- RENDER SECTIONS HELPER (For reusable components in deck & bento) ---

  const renderCalculator = () => (
    <div className={cn("p-6 sm:p-8 transition-all duration-500", t.calcCardBg)}>
      <div className="flex items-center gap-2.5 mb-6">
        <Calculator className={cn("w-6 h-6", t.accentText)} />
        <h3 className={cn("font-serif text-lg sm:text-xl font-bold", theme === "oasis" && "tracking-widest")}>
          Venture Portfolio Simulator
        </h3>
      </div>
      <p className="font-sans text-xs text-brand-light-gray/80 mb-6 leading-relaxed">
        Simulate your economic return profiles across Hamedia's direct real-asset projects:
      </p>

      {/* Profile Selector */}
      <div className="mb-6 space-y-2">
        <label className={cn("block font-serif text-[10px] sm:text-xs font-bold uppercase tracking-wider", t.accentText)}>
          Select Project Profile
        </label>
        <div className="grid grid-cols-2 gap-2">
          {[
            { id: "balanced", label: "Balanced Growth" },
            { id: "arghandab", label: "Arghandab Flagship" },
            { id: "solar", label: "Solar Infrastructure" },
            { id: "logistics", label: "Cold-Chain Logistics" },
          ].map((prof) => (
            <button
              key={prof.id}
              onClick={() => setSelectedProfile(prof.id as any)}
              className={cn(
                "px-3 py-2 text-[10px] sm:text-xs font-semibold rounded-lg border transition-all duration-300",
                selectedProfile === prof.id
                  ? (theme === "royal" ? "bg-[#10a5b2] text-white border-[#10a5b2] shadow-sm" :
                     theme === "oasis" ? "bg-[#f2b03d] text-[#121214] border-[#f2b03d] shadow-sm" :
                     "bg-[#e9595e] text-white border-[#e9595e] shadow-sm")
                  : "bg-white/5 border-white/10 text-white hover:bg-white/10"
              )}
            >
              {prof.label}
            </button>
          ))}
        </div>
      </div>

      {/* Slider */}
      <div className="mb-6">
        <div className="flex justify-between items-center mb-2">
          <label className={cn("font-serif text-[10px] sm:text-xs font-bold uppercase tracking-wider", t.accentText)}>
            Investment Amount (USD)
          </label>
          <span className="font-sans text-base font-black text-white">
            ${investmentAmount.toLocaleString()}
          </span>
        </div>
        <input
          type="range"
          min="10000"
          max="500000"
          step="10000"
          value={investmentAmount}
          onChange={(e) => setInvestmentAmount(Number(e.target.value))}
          className={cn("w-full h-1.5 bg-white/10 rounded-lg appearance-none cursor-pointer", t.sliderAccent)}
        />
        <div className="flex justify-between text-[9px] font-sans text-brand-light-gray/40 mt-1">
          <span>Min: $10k</span>
          <span>Max: $500k</span>
        </div>
      </div>

      {/* Outputs */}
      <div className="space-y-4 mb-6">
        <h4 className={cn("font-serif text-[10px] font-bold uppercase tracking-wider border-b pb-1", 
          theme === "oasis" ? "text-brand-oasis-gold border-brand-oasis-gold/20" : "border-white/10", t.accentText
        )}>
          Venture Impact Metrics
        </h4>
        <div className="grid grid-cols-2 gap-3 text-center">
          <div className={t.calcStatBg}>
            <span className={cn("block font-sans text-base font-black", t.accentText)}>
              {fundedUnits}
            </span>
            <span className="font-sans text-[8px] text-brand-light-gray/50 uppercase">{profile.unitName}</span>
          </div>
          <div className={t.calcStatBg}>
            <span className={cn("block font-sans text-base font-black", t.accentText)}>
              {profile.payback} Yrs
            </span>
            <span className="font-sans text-[8px] text-brand-light-gray/50 uppercase">Est. Payback</span>
          </div>
        </div>

        <h4 className={cn("font-serif text-[10px] font-bold uppercase tracking-wider border-b pt-2 pb-1", 
          theme === "oasis" ? "text-brand-oasis-gold border-brand-oasis-gold/20" : "border-white/10", t.accentText
        )}>
          Projected Financial Yield
        </h4>
        <div className="space-y-2 font-sans text-[11px] leading-relaxed">
          <div className="flex justify-between">
            <span className="text-brand-light-gray/70">Target Annual Yield:</span>
            <span className="font-bold text-white">{(profile.yieldRate * 100).toFixed(1)}%</span>
          </div>
          <div className="flex justify-between">
            <span className="text-brand-light-gray/70">Allocation Profile:</span>
            <span className="font-bold text-white">{profile.name}</span>
          </div>
          <div className="flex justify-between border-t border-white/10 pt-2 text-xs font-serif">
            <span className={cn("font-bold", t.accentText)}>
              Total Projected Cash-Flow:
            </span>
            <span className={cn("font-black", t.accentText)}>
              ${totalAnnualCashFlowUsd.toLocaleString()} / Yr
            </span>
          </div>
        </div>
      </div>
      <p className="font-sans text-[8px] text-brand-light-gray/40 leading-tight">
        * Projections are illustrative based on current asset prospectus yields, net of direct remote operations bookkeeping and localized security costs.
      </p>
    </div>
  );

  const renderContactForm = () => (
    <div className="w-full transition-all duration-500">
      {!formSubmitted ? (
        <form onSubmit={handleFormSubmit} className="space-y-5">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <div>
              <label className="block font-sans text-[10px] font-bold uppercase tracking-wider mb-1.5 text-slate-800">
                Full Name
              </label>
              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleFormChange}
                required
                className="w-full px-4 py-3 text-xs bg-white border border-slate-300 rounded-xl text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#10a5b2] focus:border-[#10a5b2] transition-all"
                placeholder="John Doe"
              />
            </div>
            <div>
              <label className="block font-sans text-[10px] font-bold uppercase tracking-wider mb-1.5 text-slate-800">
                Email Address
              </label>
              <input
                type="email"
                name="email"
                value={formData.email}
                onChange={handleFormChange}
                required
                className="w-full px-4 py-3 text-xs bg-white border border-slate-300 rounded-xl text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#10a5b2] focus:border-[#10a5b2] transition-all"
                placeholder="john@example.com"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <div>
              <label className="block font-sans text-[10px] font-bold uppercase tracking-wider mb-1.5 text-slate-800">
                Phone Number
              </label>
              <input
                type="tel"
                name="phone"
                value={formData.phone}
                onChange={handleFormChange}
                required
                className="w-full px-4 py-3 text-xs bg-white border border-slate-300 rounded-xl text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#10a5b2] focus:border-[#10a5b2] transition-all"
                placeholder="+1-555-555-5555"
              />
            </div>
            <div>
              <label className="block font-sans text-[10px] font-bold uppercase tracking-wider mb-1.5 text-slate-800">
                Investment Tier (USD)
              </label>
              <select
                name="interest"
                value={formData.interest}
                onChange={handleFormChange}
                className="w-full px-4 py-3 text-xs bg-white border border-slate-300 rounded-xl text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#10a5b2] focus:border-[#10a5b2] transition-all"
              >
                <option value="10k-50k">$10,000 – $50,000</option>
                <option value="50k-100k">$50,000 – $100,000</option>
                <option value="100k-250k">$100,000 – $250,000</option>
                <option value="250k+">$250,000 +</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block font-sans text-[10px] font-bold uppercase tracking-wider mb-1.5 text-slate-800">
              Inquiry Message
            </label>
            <textarea
              name="message"
              value={formData.message}
              onChange={handleFormChange}
              required
              rows={4}
              className="w-full px-4 py-3 text-xs bg-white border border-slate-300 rounded-xl text-slate-900 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-[#10a5b2] focus:border-[#10a5b2] resize-none transition-all"
              placeholder="Tell us about your interest in Hamedia agricultural & venture projects..."
            />
          </div>

          <div className="flex justify-end pt-2">
            <button
              type="submit"
              className="inline-flex items-center justify-center px-7 py-3.5 font-sans text-xs font-bold tracking-wider uppercase bg-[#10a5b2] hover:bg-[#0c8a94] text-white rounded-xl shadow-lg transition-all duration-300 hover:-translate-y-0.5"
            >
              Submit Inquiry
              <ArrowUpRight className="ml-1.5 w-4 h-4" />
            </button>
          </div>
        </form>
      ) : (
        <div className="text-center py-8 flex flex-col items-center justify-center">
          <div className="w-14 h-14 flex items-center justify-center mb-4 rounded-full bg-[#10a5b2]/10 text-[#10a5b2]">
            <CheckCircle className="w-7 h-7" />
          </div>
          <h3 className="font-sans text-lg font-bold mb-2 text-slate-900 uppercase">
            Inquiry Submitted Successfully
          </h3>
          <p className="font-sans text-xs max-w-sm mb-6 leading-relaxed text-slate-600">
            We have received your request. Our Investor Relations team will follow up via email at <strong>{formData.email}</strong>.
          </p>
          <button
            onClick={() => setFormSubmitted(false)}
            className="font-sans text-xs font-bold tracking-wider uppercase text-[#10a5b2] hover:underline"
          >
            Submit Another Inquiry
          </button>
        </div>
      )}
    </div>
  );

  return (
    <div className="w-full">
      <AnimatePresence mode="wait">
        <motion.div
          key="editorial"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3 }}
          className="w-full"
        >
          {/* 1. Hero Section (DARK) */}
          <section className="relative overflow-hidden min-h-[90vh] pt-32 pb-20 flex items-center bg-[#092227] text-white border-b border-white/10">
            {/* Background ambient lighting and grid */}
            <div className="absolute inset-0 pointer-events-none">
              <div className="absolute -top-40 left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-[#10a5b2]/20 blur-[140px] rounded-full" />
              <div className="absolute top-1/3 -right-20 w-[400px] h-[400px] bg-[#10a5b2]/10 blur-[100px] rounded-full" />
              <div className="absolute inset-0 bg-dots-white-10 opacity-10" />
            </div>

            <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-8 items-center">
                
                {/* Left Column: Hero Content */}
                <div className="lg:col-span-7 flex flex-col justify-center">
                  <span className="inline-flex items-center gap-2 px-3.5 py-1.5 text-[11px] font-bold tracking-widest uppercase mb-6 rounded-full bg-[#10a5b2]/15 text-[#10a5b2] border border-[#10a5b2]/25 w-fit">
                    <Activity className="w-4 h-4 animate-pulse" /> Launching Projects
                  </span>
                  <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black leading-[1.1] mb-6 text-white tracking-tight uppercase">
                    Building Real Assets. <br className="hidden sm:inline" />
                    Powered by <span className="text-[#10a5b2]">Remote Operations</span>.
                  </h1>
                  <p className="font-sans text-base sm:text-lg leading-relaxed text-slate-300 mb-8 max-w-xl">
                    Hamedia Investments deploys capital directly into high-yield agricultural, energy, and logistics projects across Afghanistan. By integrating Hamedia Agency's AI-enhanced remote management teams, we secure transparent and highly efficient operations from day one.
                  </p>
                  <div className="flex flex-col sm:flex-row gap-4">
                    <a 
                      href="#ventures" 
                      className="inline-flex items-center justify-center px-7 py-4 font-sans text-xs font-bold tracking-wider uppercase bg-[#10a5b2] hover:bg-[#0c8a94] text-white rounded-xl shadow-lg hover:shadow-cyan-500/20 transition-all duration-300 hover:-translate-y-0.5 group"
                    >
                      Explore Our Ventures
                      <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </a>
                    <a 
                      href="#contact" 
                      className="inline-flex items-center justify-center px-7 py-4 font-sans text-xs font-bold tracking-wider uppercase border border-white/20 hover:border-[#10a5b2] text-white hover:text-[#10a5b2] bg-white/5 backdrop-blur-sm rounded-xl transition-all duration-300"
                    >
                      Inquire Now
                    </a>
                  </div>
                </div>

                {/* Right Column: Hero Brand Showcase */}
                <div className="lg:col-span-5 flex justify-center">
                  <div className="w-full max-w-sm p-6 bg-[#0b2d34]/90 border border-white/15 backdrop-blur-md rounded-3xl shadow-2xl flex flex-col items-center text-center relative overflow-hidden group">
                    <div className="absolute inset-0 bg-gradient-to-t from-[#10a5b2]/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />
                    
                    {/* Logo with negative bottom margin to bring stripes flush to the line */}
                    <div className="w-full flex justify-center -mb-5">
                      <HamediaLogo 
                        variant="full" 
                        iconClassName="h-44 sm:h-52 w-auto object-contain" 
                        className="drop-shadow-md"
                      />
                    </div>

                    <div className="w-full pt-4 border-t border-white/10 flex flex-col gap-2 text-center font-sans relative z-10">
                      <span className="text-xs font-black tracking-widest text-[#10a5b2] uppercase">Asset-Backed Venture Platform</span>
                      <p className="text-[11px] text-slate-300 leading-relaxed">
                        Direct economic participation certificates backed by physical inventory & remote telemetry.
                      </p>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </section>

          {/* 2. Executive Vision Section (LIGHT 1) */}
          <section id="about" className="py-24 bg-[#FAF7F2] text-slate-900 border-b border-slate-200">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
                <div className="lg:col-span-5">
                  <span className="font-sans text-xs font-bold tracking-widest uppercase block mb-3 text-[#10a5b2]">Executive Vision</span>
                  <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black leading-tight text-slate-900 uppercase tracking-tight">
                    A Platform for Economic Self-Sufficiency. Built on Real Assets.
                  </h2>
                  <div className="w-16 h-1 mt-6 bg-[#10a5b2]" />
                </div>
                <div className="lg:col-span-7">
                  <p className="font-sans text-sm sm:text-base leading-relaxed mb-6 text-slate-700">
                    Hamedia Investments is focused on investing in and developing a diverse portfolio of real-asset projects across Afghanistan. Our mission is to build local economic self-sufficiency by deploying capital directly into critical productive sectors.
                  </p>
                  <p className="font-sans text-sm sm:text-base leading-relaxed mb-8 text-slate-700">
                    Under this development umbrella, we link investor capital directly to physical, revenue-generating inventory. The Arghandab Dairy Farm in Kandahar serves as our first active flagship project, establishing a proven template for our upcoming logistics, agri-tech, and energy ventures.
                  </p>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <div className="flex gap-4 p-5 bg-white border border-slate-200 rounded-2xl shadow-sm">
                      <div className="flex-shrink-0 w-10 h-10 flex items-center justify-center rounded-xl bg-[#10a5b2]/10 text-[#10a5b2] border border-[#10a5b2]/20">
                        <ShieldCheck className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className="font-sans text-sm font-bold mb-1 text-slate-900 uppercase">Asset-Backed Safety</h4>
                        <p className="font-sans text-xs leading-relaxed text-slate-600">Capital purchases physical livestock & grid components, not abstract stock.</p>
                      </div>
                    </div>
                    <div className="flex gap-4 p-5 bg-white border border-slate-200 rounded-2xl shadow-sm">
                      <div className="flex-shrink-0 w-10 h-10 flex items-center justify-center rounded-xl bg-[#10a5b2]/10 text-[#10a5b2] border border-[#10a5b2]/20">
                        <TrendingUp className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className="font-sans text-sm font-bold mb-1 text-slate-900 uppercase">Economic Participation</h4>
                        <p className="font-sans text-xs leading-relaxed text-slate-600">Direct 33% contract participation in operational cash flow.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* 3. Venture Pipelines Grid (LIGHT 2) */}
          <section id="pipelines" className="py-24 bg-white text-slate-900 border-b border-slate-200">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center max-w-3xl mx-auto mb-16">
                <span className="font-sans text-xs font-bold tracking-widest uppercase block mb-3 text-[#10a5b2]">Active & Upcoming Pipeline</span>
                <h2 className="text-3xl sm:text-4xl font-black leading-tight text-slate-900 uppercase tracking-tight">Venture Project Pipeline</h2>
                <p className="mt-3 font-sans text-sm sm:text-base leading-relaxed text-slate-600">
                  We deploy capital into key sectors powered entirely by our operational agency staff. Explore our flagship and upcoming projects below.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {/* Project 1 */}
                <div className="p-8 bg-[#FAF7F2] border border-slate-200 rounded-2xl shadow-sm flex flex-col justify-between hover:border-[#10a5b2] transition-all duration-300">
                  <div>
                    <div className="w-12 h-12 flex items-center justify-center rounded-xl mb-5 text-[#10a5b2] bg-[#10a5b2]/10 border border-[#10a5b2]/20">
                      <Wheat className="w-6 h-6" />
                    </div>
                    <span className="text-[10px] font-bold text-[#10a5b2] tracking-widest uppercase block mb-2">AgriTech & Livestock</span>
                    <h4 className="text-xl font-bold mb-3 text-slate-900">Arghandab Dairy Farm</h4>
                    <p className="font-sans text-xs leading-relaxed text-slate-600 mb-6">
                      Our active flagship project. A modern closed-loop dairy facility in Kandahar, fully operational with automated RFID tracking and smart milk flow meters.
                    </p>
                  </div>
                  <div className="flex justify-between items-center border-t border-slate-200 pt-4">
                    <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider">Status: Active</span>
                    <span className="text-xs font-black text-[#10a5b2]">14.8% Target Yield</span>
                  </div>
                </div>

                {/* Project 2 */}
                <div className="p-8 bg-[#FAF7F2] border border-slate-200 rounded-2xl shadow-sm flex flex-col justify-between hover:border-[#10a5b2] transition-all duration-300">
                  <div>
                    <div className="w-12 h-12 flex items-center justify-center rounded-xl mb-5 text-[#10a5b2] bg-[#10a5b2]/10 border border-[#10a5b2]/20">
                      <Zap className="w-6 h-6" />
                    </div>
                    <span className="text-[10px] font-bold text-[#10a5b2] tracking-widest uppercase block mb-2">Renewable Energy</span>
                    <h4 className="text-xl font-bold mb-3 text-slate-900">Kandahar Solar Grid</h4>
                    <p className="font-sans text-xs leading-relaxed text-slate-600 mb-6">
                      Developing 5MW of clean solar energy generation infrastructure to power regional storage hubs. Fully automated telemetry and remote grid monitoring.
                    </p>
                  </div>
                  <div className="flex justify-between items-center border-t border-slate-200 pt-4">
                    <span className="text-[10px] font-bold text-amber-600 uppercase tracking-wider">Status: Development</span>
                    <span className="text-xs font-black text-[#10a5b2]">12.5% Target Yield</span>
                  </div>
                </div>

                {/* Project 3 */}
                <div className="p-8 bg-[#FAF7F2] border border-slate-200 rounded-2xl shadow-sm flex flex-col justify-between hover:border-[#10a5b2] transition-all duration-300">
                  <div>
                    <div className="w-12 h-12 flex items-center justify-center rounded-xl mb-5 text-[#10a5b2] bg-[#10a5b2]/10 border border-[#10a5b2]/20">
                      <Store className="w-6 h-6" />
                    </div>
                    <span className="text-[10px] font-bold text-[#10a5b2] tracking-widest uppercase block mb-2">Cold-Chain Storage</span>
                    <h4 className="text-xl font-bold mb-3 text-slate-900">Regional Storage Nodes</h4>
                    <p className="font-sans text-xs leading-relaxed text-slate-600 mb-6">
                      A network of temperature-controlled storage warehouses for local farmers, with booking, dispatch, and energy tracking handled by Hamedia Ops.
                    </p>
                  </div>
                  <div className="flex justify-between items-center border-t border-slate-200 pt-4">
                    <span className="text-[10px] font-bold text-cyan-600 uppercase tracking-wider">Status: Engineering</span>
                    <span className="text-xs font-black text-[#10a5b2]">16.2% Target Yield</span>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* 4. The Hamedia Edge Section (DARK) */}
          <section id="operations" className="py-24 bg-[#092227] text-white border-b border-white/10">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
                <div className="lg:col-span-6 text-left">
                  <span className="font-sans text-xs font-bold tracking-widest uppercase block mb-3 text-[#10a5b2]">The Hamedia Edge</span>
                  <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black leading-tight mb-6 text-white uppercase tracking-tight">
                    AI-Enhanced Operations Engine
                  </h2>
                  <p className="font-sans text-sm sm:text-base leading-relaxed mb-8 text-slate-300">
                    Our investments succeed because we don't just supply capital—we supply complete, remote operational infrastructure. Every asset in our portfolio is optimized by Hamedia Agency's 24/7 remote experts and proprietary GrowthPilot AI software.
                  </p>
                  <div className="space-y-4 font-sans">
                    <div className="flex gap-4 items-start p-4 bg-[#0b2d34] border border-white/10 rounded-2xl">
                      <div className="w-10 h-10 flex items-center justify-center flex-shrink-0 rounded-xl bg-[#10a5b2]/15 text-[#10a5b2] border border-[#10a5b2]/20">
                        <Bot className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className="font-sans text-sm font-bold mb-1 text-white uppercase">AI-Driven Efficiencies</h4>
                        <p className="text-xs leading-relaxed text-slate-300">Automated supply tracking, resource allocation, and predictive forecasting reduce operational waste.</p>
                      </div>
                    </div>
                    <div className="flex gap-4 items-start p-4 bg-[#0b2d34] border border-white/10 rounded-2xl">
                      <div className="w-10 h-10 flex items-center justify-center flex-shrink-0 rounded-xl bg-[#10a5b2]/15 text-[#10a5b2] border border-[#10a5b2]/20">
                        <Users className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className="font-sans text-sm font-bold mb-1 text-white uppercase">24/7 Human Dispatch & Support</h4>
                        <p className="text-xs leading-relaxed text-slate-300">Remote staffing teams handle dispatch routing, security monitoring, bookkeeping, and customer support around the clock.</p>
                      </div>
                    </div>
                    <div className="flex gap-4 items-start p-4 bg-[#0b2d34] border border-white/10 rounded-2xl">
                      <div className="w-10 h-10 flex items-center justify-center flex-shrink-0 rounded-xl bg-[#10a5b2]/15 text-[#10a5b2] border border-[#10a5b2]/20">
                        <ShieldCheck className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className="font-sans text-sm font-bold mb-1 text-white uppercase">Direct Inspection & Audit</h4>
                        <p className="text-xs leading-relaxed text-slate-300">All animal health tags, milk scales, and transport trackers report directly to our cloud ledger, ensuring complete transparency.</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="lg:col-span-6 relative">
                  <div className="p-8 sm:p-10 bg-[#0b2d34] border border-white/10 rounded-3xl shadow-2xl">
                    <h3 className="text-xl font-black mb-8 text-white uppercase tracking-wider">Hamedia Active Operations</h3>
                    <div className="grid grid-cols-2 gap-5 text-center font-sans">
                      <div className="p-6 bg-[#092227] rounded-2xl border border-white/10">
                        <span className="block text-3xl font-black text-white mb-1">98%</span>
                        <span className="text-[10px] uppercase font-bold text-slate-400">Task Accuracy</span>
                      </div>
                      <div className="p-6 bg-[#092227] rounded-2xl border border-white/10">
                        <span className="block text-3xl font-black text-white mb-1">24/7</span>
                        <span className="text-[10px] uppercase font-bold text-slate-400">Live Support</span>
                      </div>
                      <div className="p-6 bg-[#092227] rounded-2xl border border-white/10">
                        <span className="block text-3xl font-black text-white mb-1">-60%</span>
                        <span className="text-[10px] uppercase font-bold text-slate-400">Operating Costs</span>
                      </div>
                      <div className="p-6 bg-[#092227] rounded-2xl border border-white/10">
                        <span className="block text-3xl font-black text-white mb-1">500+</span>
                        <span className="text-[10px] uppercase font-bold text-slate-400">Staff Deployed</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* 5. Target Industries Grid (LIGHT 1) */}
          <section id="ventures" className="py-24 bg-[#FAF7F2] text-slate-900 border-b border-slate-200">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="max-w-3xl mb-16">
                <span className="font-sans text-xs font-bold tracking-widest uppercase block mb-3 text-[#10a5b2]">Target Industries</span>
                <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black leading-tight text-slate-900 uppercase tracking-tight">
                  Deploying Capital Across High-Impact Industries
                </h2>
                <p className="mt-4 font-sans text-sm sm:text-base leading-relaxed text-slate-600">
                  We build projects and deploy capital into physical assets across primary sectors. Every venture is integrated with Hamedia's specialized remote agency operators to secure operational efficiency.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                {[
                  { 
                    name: "Agriculture & Livestock", 
                    bullets: [
                      "Verifiable RFID livestock tracking",
                      "Automated closed-loop hydroponics",
                      "Daily milk output telemetry logs"
                    ], 
                    icon: Wheat, 
                    bgImage: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80" 
                  },
                  { 
                    name: "Renewable Energy", 
                    bullets: [
                      "5MW solar utility grid generation",
                      "Smart energy storage node management",
                      "Verifiable real-time grid meter audits"
                    ], 
                    icon: Zap, 
                    bgImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=600&q=80" 
                  },
                  { 
                    name: "Food & Dairy Processing", 
                    bullets: [
                      "Automated pasteurization flow meters",
                      "Cold-chain temperature cloud ledger",
                      "B2B client shipping dispatch terminals"
                    ], 
                    icon: UtensilsCrossed, 
                    bgImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80" 
                  },
                  { 
                    name: "Transportation & Logistics", 
                    bullets: [
                      "AI-optimized cargo routing dispatch",
                      "Real-time transport container tracking",
                      "Fuel efficiency telemetry coordinates"
                    ], 
                    icon: Truck, 
                    bgImage: "https://images.unsplash.com/photo-1516528387618-afa90b13e000?auto=format&fit=crop&w=600&q=80" 
                  },
                  { 
                    name: "Real Estate & Construction", 
                    bullets: [
                      "Smart warehouse physical footprints",
                      "AI construction timeline trackers",
                      "Surveillance loops & safety audits"
                    ], 
                    icon: HomeIcon, 
                    bgImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=600&q=80" 
                  },
                  { 
                    name: "Technology & AI", 
                    bullets: [
                      "AI model server stack deployment",
                      "24/7 technical help desks",
                      "Automated cloud bookkeeper ledgers"
                    ], 
                    icon: Cpu, 
                    bgImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80" 
                  },
                  { 
                    name: "Security & Monitoring", 
                    bullets: [
                      "Live CCTV remote staffing centers",
                      "Asset access logs & security sweeps",
                      "Automatic intrusion warning loops"
                    ], 
                    icon: ShieldCheck, 
                    bgImage: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=600&q=80" 
                  },
                  { 
                    name: "Retail & Commerce", 
                    bullets: [
                      "Stock synchronization dispatch centers",
                      "B2B client distribution facilities",
                      "AI customer billing pipelines"
                    ], 
                    icon: Store, 
                    bgImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=80" 
                  },
                ].map((ind, iIdx) => {
                  const Icon = ind.icon;
                  return (
                    <div key={iIdx} className="relative overflow-hidden rounded-2xl group flex flex-col justify-between p-6 text-white border border-white/20 aspect-[4/5] sm:aspect-[3/4] md:aspect-square shadow-xl transition-all duration-300 hover:-translate-y-1 hover:border-[#10a5b2]/50 hover:shadow-cyan-500/20">
                      {/* Background Image with hover zoom */}
                      <div 
                        className="absolute inset-0 bg-cover bg-center transition-transform duration-700 group-hover:scale-110"
                        style={{ backgroundImage: `url(${ind.bgImage})` }}
                      />
                      {/* Glassy dark teal gradient overlay with backdrop blur */}
                      <div className="absolute inset-0 bg-gradient-to-b from-[#0c4d57]/70 via-[#092227]/85 to-[#051518]/95 backdrop-blur-[2px] transition-all duration-300 group-hover:via-[#092227]/75" />
                      
                      <div className="relative z-10 flex flex-col h-full justify-between">
                        <div>
                          {/* Frosted glass icon badge */}
                          <div className="w-10 h-10 flex items-center justify-center border border-white/30 bg-white/10 backdrop-blur-md rounded-xl mb-4 text-white shadow-sm">
                            <Icon className="w-5 h-5" />
                          </div>
                          
                          <h3 className="text-sm sm:text-base font-black text-white tracking-wide uppercase">{ind.name}</h3>
                          
                          <ul className="space-y-1.5 mt-3">
                            {ind.bullets.map((bullet, bIdx) => (
                              <li key={bIdx} className="flex gap-2 items-start text-[10px] sm:text-[11px] text-white/90 leading-tight">
                                <CheckCircle className="w-3.5 h-3.5 flex-shrink-0 text-[#10a5b2] mt-0.5" />
                                <span>{bullet}</span>
                              </li>
                            ))}
                          </ul>
                        </div>

                        <a 
                          href="#contact" 
                          className="mt-4 w-full py-2.5 bg-[#10a5b2] hover:bg-[#0c8a94] text-white text-[11px] font-bold rounded-xl flex items-center justify-center gap-1.5 transition-all duration-300 shadow-md uppercase tracking-wider group-hover:shadow-cyan-500/30"
                        >
                          Learn More <ArrowRight className="w-3.5 h-3.5" />
                        </a>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </section>

          {/* 6. Roadmap Model Section (LIGHT 2) */}
          <section id="model" className="py-24 bg-white text-slate-900 border-b border-slate-200">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center max-w-3xl mx-auto mb-16">
                <span className="font-sans text-xs font-bold tracking-widest uppercase block mb-3 text-[#10a5b2]">Operational Roadmap</span>
                <h2 className="text-3xl sm:text-4xl font-black leading-tight text-slate-900 uppercase tracking-tight">
                  The Hamedia Allocation Model
                </h2>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-4 gap-8 relative">
                <div className="hidden md:block absolute top-[40px] left-[15%] right-[15%] h-0.5 bg-slate-200" />
                {[
                  { num: 1, title: "Platform Setup", text: "Founders construct baseline infrastructure and facilities out of pocket." },
                  { num: 2, title: "Asset Expansion", text: "Outside investors fund active, revenue-producing inventory and assets." },
                  { num: 3, title: "Operations", text: "Hamedia Agency runs operations: remote staffing, dispatch, and bookkeeping." },
                  { num: 4, title: "Yield", text: "Quarterly distributions are disbursed directly to certificate holders." }
                ].map((step, sIdx) => (
                  <div key={sIdx} className="flex flex-col items-center text-center relative z-10">
                    <div className="w-16 h-16 border-2 border-[#10a5b2] bg-[#FAF7F2] flex items-center justify-center font-sans text-xl font-black mb-4 shadow-md rounded-2xl text-[#10a5b2]">
                      {step.num}
                    </div>
                    <h3 className="font-sans text-base font-bold mb-2 text-slate-900 uppercase">{step.title}</h3>
                    <p className="font-sans text-xs leading-relaxed px-4 text-slate-600">{step.text}</p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* 7. Flagship Project Section & Calculator (DARK) */}
          <section id="flagship" className="py-24 bg-[#092227] text-white border-b border-white/10 relative overflow-hidden">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
              <div className="text-center max-w-3xl mx-auto mb-16">
                <span className="font-sans text-xs font-bold tracking-widest uppercase block mb-3 text-[#10a5b2]">Active Flagship Blueprint</span>
                <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black leading-tight text-white uppercase tracking-tight">Arghandab Dairy Farm</h2>
                <p className="mt-4 font-sans text-sm sm:text-base leading-relaxed text-slate-300">
                  Arghandab Dairy Farm in Kandahar is our active flagship venture. It serves as our operational blueprint, proving how direct physical asset tracking combined with remote back-office staffing generates stable, cash-yielding returns.
                </p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
                <div className="lg:col-span-6 flex flex-col justify-center">
                  <div className="p-8 bg-[#0b2d34] border border-white/10 rounded-3xl shadow-xl">
                    <span className="inline-flex px-3.5 py-1.5 rounded-full font-sans text-[10px] font-bold tracking-widest uppercase mb-4 bg-[#10a5b2]/15 text-[#10a5b2] border border-[#10a5b2]/20">Venture Return Model</span>
                    <h3 className="text-2xl font-black mb-6 text-white uppercase tracking-wide">Asset-Backed Return Structure</h3>
                    
                    <ul className="space-y-5">
                      <li className="flex gap-4">
                        <CheckCircle className="w-6 h-6 flex-shrink-0 mt-0.5 text-[#10a5b2]" />
                        <div>
                          <h4 className="font-sans text-sm font-bold text-white uppercase">33% Productive Asset Yield</h4>
                          <p className="font-sans text-xs text-slate-300 mt-1">Direct quarterly distributions from primary operational cash flows (milk sales, energy grid sales, cold-storage leases).</p>
                        </div>
                      </li>
                      <li className="flex gap-4">
                        <CheckCircle className="w-6 h-6 flex-shrink-0 mt-0.5 text-[#10a5b2]" />
                        <div>
                          <h4 className="font-sans text-sm font-bold text-white uppercase">33% Asset Growth Appreciation</h4>
                          <p className="font-sans text-xs text-slate-300 mt-1">Net value distributions from secondary growth lines, herd reproduction, and utility expansions.</p>
                        </div>
                      </li>
                      <li className="flex gap-4">
                        <CheckCircle className="w-6 h-6 flex-shrink-0 mt-0.5 text-[#10a5b2]" />
                        <div>
                          <h4 className="font-sans text-sm font-bold text-white uppercase">33% Net Asset Divestment Value</h4>
                          <p className="font-sans text-xs text-slate-300 mt-1">Divestment exit values calculated based on the verified market valuation of the physical project assets funded.</p>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>

                {/* Calculator Widget */}
                <div className="lg:col-span-6">
                  {renderCalculator()}
                </div>
              </div>
            </div>
          </section>

          {/* 8. FAQ Section (LIGHT 1) */}
          <section id="faq" className="py-24 bg-[#FAF7F2] text-slate-900 border-b border-slate-200">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center mb-16">
                <HelpCircle className="w-10 h-10 text-[#10a5b2] mx-auto mb-4" />
                <h2 className="font-sans text-3xl sm:text-4xl font-black text-slate-900 uppercase tracking-tight">Frequently Asked Questions</h2>
              </div>
              <div className="space-y-4">
                {faqs.map((faq, idx) => (
                  <div key={idx} className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm transition-all duration-300">
                    <button
                      onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                      className="w-full flex items-center justify-between p-6 text-left font-sans text-sm sm:text-base font-bold text-slate-900 hover:text-[#10a5b2] transition-colors duration-200"
                    >
                      <span>{faq.question}</span>
                      <ChevronDown className={cn("w-5 h-5 text-slate-400 transition-transform duration-300", openFaq === idx && "transform rotate-180 text-[#10a5b2]")} />
                    </button>
                    <AnimatePresence initial={false}>
                      {openFaq === idx && (
                        <motion.div
                          initial={{ height: 0 }}
                          animate={{ height: "auto" }}
                          exit={{ height: 0 }}
                          className="overflow-hidden"
                        >
                          <div className="p-6 pt-0 border-t border-slate-100 font-sans text-xs sm:text-sm leading-relaxed text-slate-600">{faq.answer}</div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* 9. Contact Section (LIGHT 2) */}
          <section id="contact" className="py-24 bg-white text-slate-900">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="text-center max-w-2xl mx-auto mb-16">
                <span className="font-sans text-xs font-bold tracking-widest uppercase block mb-3 text-[#10a5b2]">Join Our Network</span>
                <h2 className="text-3xl sm:text-4xl font-black leading-tight text-slate-900 uppercase tracking-tight">
                  Investor Relations Inquiry
                </h2>
                <p className="mt-4 font-sans text-xs sm:text-sm leading-relaxed text-slate-600">
                  If you are interested in passive, asset-backed economic participation, please submit an inquiry form below.
                </p>
              </div>
              <div className="bg-[#FAF7F2] border border-slate-200 rounded-3xl p-8 sm:p-10 shadow-xl">
                {renderContactForm()}
              </div>
            </div>
          </section>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
