"use client";

import React, { useState } from "react";
import { HamediaLogo } from "@/components/ui/HamediaLogo";
import { 
  ArrowRight, 
  TrendingUp, 
  Sprout, 
  ShieldCheck, 
  Users, 
  Building,
  CheckCircle,
  Activity,
  Calculator,
  ChevronDown,
  Mail,
  Phone,
  HelpCircle,
  ArrowUpRight,
  BookOpen,
  Send,
  Layers,
  MapPin,
  ClipboardList,
  Flame,
  Award,
  Bot,
  Truck,
  Cpu,
  Home as HomeIcon,
  Wheat
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { toast } from "sonner";
import { useDesign, DesignVariant, StructureVariant } from "@/components/providers/DesignContext";
import { cn } from "@/lib/utils";

// FAQ type definition
interface FAQItem {
  question: string;
  answer: string;
}

export default function Home() {
  const { theme, structure } = useDesign();

  // --- SHARED STATE ---
  const [investmentAmount, setInvestmentAmount] = useState<number>(50000);
  const exchangeRate = 65; // AFN per USD

  // Calculations based on prospectus
  const scale = investmentAmount / 100000;
  const productiveCows = Math.max(1, Math.round(18 * scale));
  const youngerHeifers = Math.max(0, Math.round(11 * scale));
  const totalCattle = productiveCows + youngerHeifers;

  const annualMilkLiters = productiveCows * 30 * 300;
  const totalMilkRevenueAfn = annualMilkLiters * 28;
  const investorMilkRevenueAfn = Math.round(totalMilkRevenueAfn * 0.33);
  const investorMilkRevenueUsd = Math.round(investorMilkRevenueAfn / exchangeRate);

  const annualMaleCalves = Math.round((productiveCows * 0.5) * 10) / 10;
  const investorMaleCalfRevenueAfn = Math.round((annualMaleCalves * 110000) * 0.33);
  const investorMaleCalfRevenueUsd = Math.round(investorMaleCalfRevenueAfn / exchangeRate);

  const totalAnnualCashFlowUsd = investorMilkRevenueUsd + investorMaleCalfRevenueUsd;

  // Contact Form States
  const [formSubmitted, setFormSubmitted] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    interest: "50k-100k",
    message: "",
  });

  const handleFormChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormSubmitted(true);
    toast.success("Thank you for your inquiry! Our investor relations representative will contact you shortly.");
  };

  // FAQ State
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const faqs: FAQItem[] = [
    {
      question: "Do I acquire equity in the business or ownership of the land?",
      answer: "No. The Economic Participation Model is structured so that investor capital goes directly to purchasing active operational inventory (such as livestock herd lines or energy components). You receive an Economic Participation Certificate giving you a contractual interest in the net benefits generated by that specific asset line. The land, physical facilities, and corporate entities remain 100% owned and controlled by the founders."
    },
    {
      question: "What is the minimum term of the investment and exit process?",
      answer: "The minimum intended term is 2.5 years to allow the project's assets to mature and stabilize. However, you can request divestment after 1 year. The company intends to accommodate divestment requests within 90 days, calculating your exit value based on your contractual interest in the current market value of the assets."
    },
    {
      question: "How are project assets tracked and reported?",
      answer: "We employ modern digital tracking technology. For livestock, every animal receives a digital RFID ear tag; for logistics and energy projects, smart flow meters and GPS trackers report directly to our cloud ledger. Investors receive regular operational summaries, yield logs, and are welcome to conduct site inspections."
    },
    {
      question: "How are direct operating costs accounted for?",
      answer: "Operating costs (such as feed, veterinary care, panel maintenance, or fuel) are charged directly to that specific project line. Net distributions are calculated after these direct costs are deducted from project revenue, ensuring investors do not subsidize unrelated general platform development."
    },
    {
      question: "What operational risks are involved?",
      answer: "Productive real-asset projects involve natural, biological, and market risks. Risk is shared proportionally. Because the investor holds a certificate interest in a specific asset line, both the company and the investor absorb outcomes matching that project's real performance."
    }
  ];

  // --- THEME-SPECIFIC DESIGN TOKENS ---
  const getThemeStyles = () => {
    switch (theme) {
      case "royal":
        return {
          bodyBg: "bg-slate-50",
          textCharcoal: "text-slate-900",
          textGray: "text-slate-600",
          headingFont: "font-sans font-black tracking-tight",
          sectionHeadingClass: "font-sans font-black tracking-tight text-[#10a5b2] uppercase",
          subTitleClass: "text-[#10a5b2]",
          dividerClass: "bg-[#10a5b2]",
          // Hero specific
          heroLeftBg: "bg-white",
          heroRightBg: "bg-gradient-to-br from-[#10a5b2] via-[#0d8a94] to-[#0c1626]",
          heroTextClass: "font-sans font-black tracking-tight text-white uppercase",
          heroGridClass: "",
          accentText: "text-[#10a5b2]",
          primaryBtn: "bg-[#10a5b2] hover:bg-[#0d8a94] text-white rounded-lg shadow-sm",
          secondaryBtn: "border border-white/30 hover:border-white bg-white/5 hover:bg-white/10 text-white rounded-lg",
          badgeClass: "bg-[#10a5b2]/10 text-[#10a5b2] border border-[#10a5b2]/20 rounded-md",
          cardClass: "bg-white border border-slate-100 rounded-lg shadow-sm hover:shadow-md",
          iconContainer: "bg-[#10a5b2]/10 text-[#10a5b2] rounded-lg",
          checkIcon: "text-[#10a5b2]",
          // Calculator specific
          calcCardBg: "bg-[#0c1626] text-white rounded-lg shadow-lg border border-slate-800",
          sliderAccent: "accent-[#10a5b2]",
          calcStatBg: "bg-white/5 border border-white/10 rounded-md",
          // Form specific
          formBg: "bg-white border border-slate-100 rounded-xl p-8 shadow-sm",
          inputClass: "bg-slate-50 border border-slate-200 rounded-lg text-slate-800 focus:ring-[#10a5b2]",
          formBtn: "bg-[#10a5b2] hover:bg-[#0d8a94] text-white rounded-lg shadow-sm",
          faqClass: "bg-white border border-slate-100 rounded-lg",
          slideLeftPanelBg: "bg-white border border-slate-100 rounded-lg shadow-sm",
        };
      case "oasis":
        return {
          bodyBg: "bg-[#121214]",
          textCharcoal: "text-white",
          textGray: "text-gray-300",
          headingFont: "font-serif font-bold tracking-widest",
          sectionHeadingClass: "font-serif text-[#f2b03d] uppercase tracking-widest",
          subTitleClass: "text-[#f2b03d]",
          dividerClass: "bg-[#f2b03d]",
          // Hero specific
          heroLeftBg: "bg-[#121214] border-r border-white/5",
          heroRightBg: "bg-[#1a1a1c]",
          heroTextClass: "font-serif font-bold tracking-widest text-white",
          heroGridClass: "border border-white/5",
          accentText: "text-[#f2b03d]",
          primaryBtn: "bg-[#f2b03d] hover:bg-[#d69624] text-black font-black border-0 rounded-lg shadow-sm",
          secondaryBtn: "border border-white/20 hover:border-white text-white bg-transparent rounded-lg",
          badgeClass: "bg-[#f2b03d]/10 text-[#f2b03d] border border-[#f2b03d]/20 rounded-lg",
          cardClass: "glass-dark border border-white/10 rounded-xl hover:bg-white/5 transition-all duration-300 shadow-lg",
          iconContainer: "glass text-[#f2b03d] rounded-lg border border-white/10",
          checkIcon: "text-[#f2b03d]",
          // Calculator specific
          calcCardBg: "glass-dark border border-white/10 text-white rounded-xl shadow-2xl",
          sliderAccent: "accent-[#f2b03d]",
          calcStatBg: "glass border border-white/10 rounded-lg",
          // Form specific
          formBg: "glass-dark border border-white/10 text-white rounded-xl shadow-2xl p-8",
          inputClass: "glass border border-white/10 rounded-lg text-white focus:ring-[#f2b03d]",
          formBtn: "bg-[#f2b03d] hover:bg-[#d69624] text-black font-black rounded-lg border-0 shadow-sm",
          faqClass: "glass-dark border border-white/10 rounded-lg text-white",
          slideLeftPanelBg: "glass-dark border border-white/10 text-white rounded-xl shadow-lg",
        };
      case "heritage":
      default:
        return {
          bodyBg: "bg-gradient-to-br from-[#FAF8F5] to-[#f5e0b9]/30",
          textCharcoal: "text-slate-800",
          textGray: "text-slate-600",
          headingFont: "font-serif font-black",
          sectionHeadingClass: "font-sans font-bold tracking-widest text-[#e9595e] uppercase",
          subTitleClass: "text-[#e9595e]",
          dividerClass: "bg-[#e9595e]",
          // Hero specific
          heroLeftBg: "bg-[#FAF8F5] lg:diagonal-cut-banner-left lg:pr-24",
          heroRightBg: "bg-[#e9595e] text-white lg:diagonal-cut-banner-right lg:pl-32",
          heroTextClass: "font-serif font-black text-white",
          heroGridClass: "",
          accentText: "text-[#e9595e]",
          primaryBtn: "bg-[#e9595e] hover:bg-[#d64c51] text-white font-bold rounded-lg shadow-md hover:shadow-lg transition-transform border-0",
          secondaryBtn: "border border-slate-300 hover:border-[#e9595e] text-slate-700 hover:text-[#e9595e] bg-transparent rounded-lg",
          badgeClass: "bg-[#e9595e]/10 text-[#e9595e] border border-[#e9595e]/25 rounded-full",
          cardClass: "bg-white border border-slate-100 rounded-xl shadow-sm hover:shadow-md",
          iconContainer: "bg-[#e9595e]/10 text-[#e9595e] rounded-lg",
          checkIcon: "text-[#e9595e]",
          // Calculator specific
          calcCardBg: "bg-slate-900 text-white rounded-2xl shadow-xl",
          sliderAccent: "accent-[#e9595e]",
          calcStatBg: "bg-white/5 border border-white/5 rounded-lg",
          // Form specific
          formBg: "bg-[#FAF8F5] border border-slate-200 p-8 rounded-2xl shadow-md",
          inputClass: "bg-white border border-slate-200 rounded-lg text-slate-800 focus:ring-[#e9595e]",
          formBtn: "bg-[#e9595e] hover:bg-[#d64c51] text-white rounded-lg shadow-md",
          faqClass: "bg-white border border-slate-100 rounded-xl",
          slideLeftPanelBg: "bg-[#FAF8F5] border border-slate-200 rounded-2xl shadow-sm",
        };
    }
  };

  const t = getThemeStyles();

  // --- RENDER SECTIONS HELPER (For reusable components in deck & bento) ---

  const renderCalculator = () => (
    <div className={cn("p-6 sm:p-8 transition-all duration-500", t.calcCardBg)}>
      <div className="flex items-center gap-2.5 mb-6">
        <Calculator className={cn("w-6 h-6", theme === "royal" ? "text-brand-blue" : "text-brand-gold")} />
        <h3 className={cn("font-serif text-lg sm:text-xl font-bold", theme === "oasis" && "tracking-widest")}>
          Herd Investment Simulator
        </h3>
      </div>
      <p className="font-sans text-xs text-brand-light-gray/80 mb-6 leading-relaxed">
        Simulate the economic scale of your cow-line based on the $100k illustrative prospectus:
      </p>

      {/* Slider */}
      <div className="mb-6">
        <div className="flex justify-between items-center mb-2">
          <label className={cn("font-serif text-[10px] sm:text-xs font-bold uppercase tracking-wider", 
            theme === "royal" ? "text-brand-blue" : theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-gold"
          )}>
            Capital (USD)
          </label>
          <span className="font-sans text-base font-black text-white">
            ${investmentAmount.toLocaleString()}
          </span>
        </div>
        <input
          type="range"
          min="10000"
          max="500000"
          step="10000"
          value={investmentAmount}
          onChange={(e) => setInvestmentAmount(Number(e.target.value))}
          className={cn("w-full h-1.5 bg-white/10 rounded-lg appearance-none cursor-pointer", t.sliderAccent)}
        />
        <div className="flex justify-between text-[9px] font-sans text-brand-light-gray/40 mt-1">
          <span>Min: $10k</span>
          <span>Max: $500k</span>
        </div>
      </div>

      {/* Outputs */}
      <div className="space-y-4 mb-6">
        <h4 className={cn("font-serif text-[10px] font-bold uppercase tracking-wider border-b pb-1", 
          theme === "royal" ? "text-brand-blue border-white/10" : theme === "oasis" ? "text-brand-oasis-gold border-brand-oasis-gold/20" : "text-brand-gold border-white/10"
        )}>
          Herd Scale
        </h4>
        <div className="grid grid-cols-3 gap-3 text-center">
          <div className={t.calcStatBg}>
            <span className={cn("block font-sans text-base font-black", theme === "royal" ? "text-brand-blue" : theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-gold")}>
              {productiveCows}
            </span>
            <span className="font-sans text-[8px] text-brand-light-gray/50 uppercase">Cows</span>
          </div>
          <div className={t.calcStatBg}>
            <span className={cn("block font-sans text-base font-black", theme === "royal" ? "text-brand-blue" : theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-gold")}>
              {youngerHeifers}
            </span>
            <span className="font-sans text-[8px] text-brand-light-gray/50 uppercase">Heifers</span>
          </div>
          <div className={t.calcStatBg}>
            <span className={cn("block font-sans text-base font-black", theme === "royal" ? "text-brand-blue" : theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-gold")}>
              {totalCattle}
            </span>
            <span className="font-sans text-[8px] text-brand-light-gray/50 uppercase">Total</span>
          </div>
        </div>

        <h4 className={cn("font-serif text-[10px] font-bold uppercase tracking-wider border-b pt-2 pb-1", 
          theme === "royal" ? "text-brand-blue border-white/10" : theme === "oasis" ? "text-brand-oasis-gold border-brand-oasis-gold/20" : "text-brand-gold border-white/10"
        )}>
          Projected Annual Cash-Flow (33% Share)
        </h4>
        <div className="space-y-2 font-sans text-[11px] leading-relaxed">
          <div className="flex justify-between">
            <span className="text-brand-light-gray/70">Milk operational yield:</span>
            <span className="font-bold text-white">${investorMilkRevenueUsd.toLocaleString()}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-brand-light-gray/70">Male calves sold:</span>
            <span className="font-bold text-white">${investorMaleCalfRevenueUsd.toLocaleString()}</span>
          </div>
          <div className="flex justify-between border-t border-white/10 pt-2 text-xs font-serif">
            <span className={cn("font-bold", theme === "royal" ? "text-brand-blue" : theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-gold")}>
              Total Projected Cash-Flow:
            </span>
            <span className={cn("font-black", theme === "royal" ? "text-brand-blue" : theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-gold")}>
              ${totalAnnualCashFlowUsd.toLocaleString()} / Yr
            </span>
          </div>
        </div>
      </div>
      <p className="font-sans text-[8px] text-brand-light-gray/40 leading-tight">
        * Projections are illustrative based on 30L/day milk at 28 AFN/L, operating costs at 66,857 AFN/head, and exchange rate of 65 AFN/USD.
      </p>
    </div>
  );

  const renderContactForm = () => (
    <div className={cn("transition-all duration-500", t.formBg)}>
      {!formSubmitted ? (
        <form onSubmit={handleFormSubmit} className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={cn("block font-sans text-[9px] font-bold uppercase tracking-wider mb-1.5", 
                theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-charcoal"
              )}>
                Full Name
              </label>
              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleFormChange}
                required
                className={cn("w-full px-3 py-2.5 text-xs focus:outline-none focus:ring-1 transition-all duration-500", t.inputClass)}
                placeholder="John Doe"
              />
            </div>
            <div>
              <label className={cn("block font-sans text-[9px] font-bold uppercase tracking-wider mb-1.5", 
                theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-charcoal"
              )}>
                Email
              </label>
              <input
                type="email"
                name="email"
                value={formData.email}
                onChange={handleFormChange}
                required
                className={cn("w-full px-3 py-2.5 text-xs focus:outline-none focus:ring-1 transition-all duration-500", t.inputClass)}
                placeholder="john@example.com"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className={cn("block font-sans text-[9px] font-bold uppercase tracking-wider mb-1.5", 
                theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-charcoal"
              )}>
                Phone
              </label>
              <input
                type="tel"
                name="phone"
                value={formData.phone}
                onChange={handleFormChange}
                required
                className={cn("w-full px-3 py-2.5 text-xs focus:outline-none focus:ring-1 transition-all duration-500", t.inputClass)}
                placeholder="+1-555-555-5555"
              />
            </div>
            <div>
              <label className={cn("block font-sans text-[9px] font-bold uppercase tracking-wider mb-1.5", 
                theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-charcoal"
              )}>
                Investment Tier (USD)
              </label>
              <select
                name="interest"
                value={formData.interest}
                onChange={handleFormChange}
                className={cn("w-full px-3 py-2.5 text-xs focus:outline-none focus:ring-1 transition-all duration-500", t.inputClass)}
              >
                <option value="10k-50k">$10k – $50k</option>
                <option value="50k-100k">$50k – $100k</option>
                <option value="100k-250k">$100k – $250k</option>
                <option value="250k+">$250k +</option>
              </select>
            </div>
          </div>

          <div>
            <label className={cn("block font-sans text-[9px] font-bold uppercase tracking-wider mb-1.5", 
              theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-charcoal"
            )}>
              Inquiry Message
            </label>
            <textarea
              name="message"
              value={formData.message}
              onChange={handleFormChange}
              required
              rows={3}
              className={cn("w-full px-3 py-2.5 text-xs focus:outline-none focus:ring-1 resize-none transition-all duration-500", t.inputClass)}
              placeholder="Tell us about your interest in agricultural investments..."
            />
          </div>

          <div className="flex justify-end pt-2">
            <button
              type="submit"
              className={cn("inline-flex items-center justify-center px-5 py-2.5 font-sans text-xs font-bold tracking-wider uppercase transition-all duration-300", t.formBtn)}
            >
              Submit Inquiry
              <ArrowUpRight className="ml-1.5 w-4 h-4" />
            </button>
          </div>
        </form>
      ) : (
        <div className="text-center py-6 flex flex-col items-center justify-center">
          <div className="w-12 h-12 flex items-center justify-center mb-4 rounded-full bg-brand-blue/10 text-brand-blue">
            <CheckCircle className="w-6 h-6" />
          </div>
          <h3 className={cn("font-serif text-base font-bold mb-1", t.textCharcoal)}>
            Inquiry Submitted
          </h3>
          <p className={cn("font-sans text-[11px] max-w-sm mb-4 leading-relaxed", t.textGray)}>
            We have received your request. Our Investor Relations team will follow up via email at <strong>{formData.email}</strong>.
          </p>
          <button
            onClick={() => setFormSubmitted(false)}
            className="font-sans text-[10px] font-bold tracking-wider uppercase text-brand-blue hover:text-brand-blue-dark"
          >
            Submit Another Inquiry
          </button>
        </div>
      )}
    </div>
  );

  return (
    <div className="w-full">
      <AnimatePresence mode="wait">
        
        {/* ============================================================
            STRUCTURE 1: EDITORIAL LANDING PAGE (DEFAULT)
            ============================================================ */}
        {structure === "structure1" && (
          <motion.div
            key="structure1"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="w-full"
          >
            {/* 1. Hero Section */}
            <section className={cn(
              "relative overflow-hidden min-h-[85vh] flex items-center border-b border-brand-charcoal/5 transition-colors duration-500",
              theme === "royal" ? "bg-slate-50" : theme === "oasis" ? "bg-brand-oasis-bg" : "bg-brand-cream-light"
            )}>
              <div className="absolute inset-0 pointer-events-none">
                {theme === "royal" ? (
                  <div className="absolute inset-0 bg-grid-charcoal-40 opacity-20" />
                ) : theme === "oasis" ? (
                  <div className="absolute inset-0 bg-dots-gold-20 opacity-5" />
                ) : (
                  <div className="absolute inset-0 bg-dots-charcoal-10 opacity-50" />
                )}
              </div>

              <div className="w-full max-w-[1440px] mx-auto grid grid-cols-1 lg:grid-cols-12 relative min-h-[85vh] lg:min-h-0">
                <div className={cn("col-span-1 lg:col-span-5 flex flex-col justify-center items-center p-8 sm:p-12 lg:p-16 z-25 transition-all duration-500", t.heroLeftBg)}>
                  <div className="text-center flex flex-col items-center">
                    <HamediaLogo 
                      variant="full" 
                      iconClassName="w-32 h-32 md:w-36 md:h-36" 
                      className="mb-4"
                      titleClassName="text-2xl md:text-3xl mt-3"
                      subtitleClassName="text-[10px] md:text-xs mt-1"
                      stripesClassName="w-20 md:w-24 mt-2"
                    />
                    <div className={cn("h-0.5 w-16 my-4 hidden lg:block transition-all duration-500", t.dividerClass)} />
                    <p className={cn("font-sans text-xs sm:text-sm font-bold tracking-[0.2em] uppercase max-w-sm transition-colors duration-500", 
                      theme === "royal" ? "text-brand-navy" : theme === "oasis" ? "text-brand-oasis-gold" : "text-brand-blue"
                    )}>
                      Afghanistan Investment Arm
                    </p>
                  </div>
                </div>

                <div className={cn("col-span-1 lg:col-span-7 flex flex-col justify-center p-8 sm:p-12 lg:p-16 z-10 relative transition-all duration-500", t.heroRightBg)}>
                  {theme === "royal" ? (
                    <div className="absolute inset-0 bg-dots-white-10 opacity-5 pointer-events-none" />
                  ) : theme === "oasis" ? (
                    <div className="absolute inset-0 border-8 border-brand-oasis-gold/10 m-4 pointer-events-none" />
                  ) : (
                    <>
                      <div className="absolute inset-0 bg-dots-white-10 opacity-15 pointer-events-none" />
                      <div className="absolute right-0 top-0 bottom-0 w-8 md:w-16 bg-brand-cream-dark/20 flex flex-col gap-6 items-center justify-center opacity-40 pointer-events-none">
                        <div className="w-2 md:w-4 h-32 bg-brand-cream-light transform rotate-12 shadow-lg" />
                        <div className="w-2 md:w-4 h-32 bg-brand-cream-light transform rotate-12 shadow-lg" />
                      </div>
                    </>
                  )}

                  <div className={cn("max-w-2xl relative z-10", theme === "oasis" && "p-6 border border-[#D4A218]/20 bg-[#FAF6EE]")}>
                    <span className={cn("inline-flex items-center gap-1.5 px-3 py-1 text-[10px] font-bold tracking-widest uppercase mb-6", t.badgeClass)}>
                      <Activity className="w-3.5 h-3.5 animate-pulse" /> Launching Projects
                    </span>
                    <h1 className={cn("text-3xl sm:text-4xl lg:text-5xl leading-[1.1] mb-6 transition-all duration-500", t.heroTextClass)}>
                      Investing in the Future of <br className="hidden sm:inline" />
                      <span className={t.accentText}>Afghanistan's</span> Real Assets
                    </h1>
                    <p className={cn("font-sans text-sm sm:text-base leading-relaxed mb-8 max-w-xl transition-all duration-500", 
                      theme === "royal" ? "text-slate-300" : theme === "oasis" ? "text-[#4E3E2F]/90" : "text-brand-cream-light/90"
                    )}>
                      Hamedia Investments structures high-impact, asset-backed opportunities. We empower agricultural, livestock, and energy projects—starting with Kandahar's flagship Arghandab Dairy Farm—to deliver sustainable passive economic yields.
                    </p>
                    <div className="flex flex-col sm:flex-row gap-4">
                      <a href="#flagship" className={cn("inline-flex items-center justify-center px-6 py-3.5 font-sans text-xs font-bold tracking-wider uppercase shadow-md transition-all duration-300 hover:-translate-y-0.5 group", t.primaryBtn)}>
                        View Flagship Project
                        <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
                      </a>
                      <a href="#contact" className={cn("inline-flex items-center justify-center px-6 py-3.5 font-sans text-xs font-bold tracking-wider uppercase transition-all duration-300", t.secondaryBtn)}>
                        Inquire Now
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* 2. Executive Vision Section */}
            <section id="about" className="py-20 border-b border-brand-charcoal/5">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
                  <div className="lg:col-span-5">
                    <span className={cn("font-sans text-xs font-bold tracking-widest uppercase block mb-3", t.subTitleClass)}>Executive Vision</span>
                    <h2 className={cn("text-2xl sm:text-3xl lg:text-4xl leading-tight transition-all duration-500", t.headingFont, t.textCharcoal)}>
                      A Platform for Economic Self-Sufficiency. Built on Real Assets.
                    </h2>
                    <div className={cn("w-16 h-1 mt-6 transition-all duration-500", t.dividerClass)} />
                  </div>
                  <div className="lg:col-span-7">
                    <p className={cn("font-sans text-sm sm:text-base leading-relaxed mb-6 transition-all duration-500", t.textGray)}>
                      Hamedia Investments is focused on investing in and developing a diverse portfolio of real-asset projects across Afghanistan. Our mission is to build local economic self-sufficiency by deploying capital directly into critical productive sectors.
                    </p>
                    <p className={cn("font-sans text-sm sm:text-base leading-relaxed mb-8 transition-all duration-500", t.textGray)}>
                      Under this development umbrella, we link investor capital directly to physical, revenue-generating inventory. The Arghandab Dairy Farm in Kandahar serves as our first active flagship project, establishing a proven template for our upcoming logistics, agri-tech, and energy ventures.
                    </p>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                      <div className="flex gap-4">
                        <div className={cn("flex-shrink-0 w-10 h-10 flex items-center justify-center transition-all duration-500", t.iconContainer)}>
                          <ShieldCheck className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>Asset-Backed Safety</h4>
                          <p className={cn("font-sans text-xs leading-relaxed transition-colors duration-500", t.textGray)}>Capital purchases physical livestock, not abstract stock.</p>
                        </div>
                      </div>
                      <div className="flex gap-4">
                        <div className={cn("flex-shrink-0 w-10 h-10 flex items-center justify-center transition-all duration-500", t.iconContainer)}>
                          <TrendingUp className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>Economic Participation</h4>
                          <p className={cn("font-sans text-xs leading-relaxed transition-colors duration-500", t.textGray)}>Direct 33% contract participation in operational output.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* 3. Flagship Project Section */}
            <section id="flagship" className={cn("py-20 relative overflow-hidden transition-colors duration-500", 
              theme === "oasis" ? "bg-[#FAF6EE] text-[#4E3E2F]" : "bg-white"
            )}>
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
                <div className="text-center max-w-3xl mx-auto mb-16">
                  <span className={cn("font-sans text-xs font-bold tracking-widest uppercase block mb-3", t.subTitleClass)}>First Flagship Venture</span>
                  <h2 className={cn("text-3xl sm:text-4xl font-black leading-tight transition-colors duration-500", 
                    theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal", t.headingFont
                  )}>Arghandab Dairy Farm</h2>
                  <p className={cn("mt-4 font-sans text-sm sm:text-base leading-relaxed transition-colors duration-500",
                    theme === "oasis" ? "text-[#4E3E2F]/80" : "text-brand-gray"
                  )}>
                    Based in Kandahar, Arghandab Dairy Farm is a modern, closed-loop livestock expansion opportunity. Investors bypass infrastructure and buy directly into the dairy herd.
                  </p>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
                  <div className="lg:col-span-6 flex flex-col justify-center">
                    <div className={cn("p-6 sm:p-8 border transition-all duration-500", 
                      theme === "royal" ? "bg-white border-slate-200 rounded-lg shadow-sm" : 
                      theme === "oasis" ? "bg-[#FAF6EE] border-[#D4A218]/20 rounded-none shadow-sm" : 
                      "bg-brand-cream/80 border-brand-charcoal/5 rounded-2xl glass-card"
                    )}>
                      <span className={cn("inline-flex px-3 py-1 rounded font-sans text-[10px] font-bold tracking-widest uppercase mb-4",
                        theme === "royal" ? "bg-brand-blue/10 text-brand-blue" : 
                        theme === "oasis" ? "bg-brand-oasis-gold/10 text-brand-oasis-gold" : 
                        "bg-brand-red/10 text-brand-red"
                      )}>Economic Participation Model</span>
                      <h3 className={cn("text-xl sm:text-2xl font-bold mb-4 font-serif transition-colors duration-500", 
                        theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal"
                      )}>The Cow-Line 33% Structure</h3>
                      
                      <ul className="space-y-4">
                        <li className="flex gap-3">
                          <CheckCircle className={cn("w-5 h-5 flex-shrink-0 mt-0.5", t.checkIcon)} />
                          <div>
                            <h4 className={cn("font-serif text-xs sm:text-sm font-bold", theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal")}>33% Milk Operational distributions</h4>
                            <p className={cn("font-sans text-[11px] sm:text-xs", theme === "oasis" ? "text-[#4E3E2F]/80" : "text-brand-gray")}>Net cash yield attributable to investor-funded cows after direct cost accounting.</p>
                          </div>
                        </li>
                        <li className="flex gap-3">
                          <CheckCircle className={cn("w-5 h-5 flex-shrink-0 mt-0.5", t.checkIcon)} />
                          <div>
                            <h4 className={cn("font-serif text-xs sm:text-sm font-bold", theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal")}>33% Male Offspring value</h4>
                            <p className={cn("font-sans text-[11px] sm:text-xs", theme === "oasis" ? "text-[#4E3E2F]/80" : "text-brand-gray")}>Realized sale values from male calves raised and sold at ~2 years old.</p>
                          </div>
                        </li>
                        <li className="flex gap-3">
                          <CheckCircle className={cn("w-5 h-5 flex-shrink-0 mt-0.5", t.checkIcon)} />
                          <div>
                            <h4 className={cn("font-serif text-xs sm:text-sm font-bold", theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal")}>33% Herd Exit Value</h4>
                            <p className={cn("font-sans text-[11px] sm:text-xs", theme === "oasis" ? "text-[#4E3E2F]/80" : "text-brand-gray")}>Divestment calculated based on current market valuation of livestock in your herd line.</p>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>

                  {/* Calculator Widget */}
                  <div className="lg:col-span-6">
                    {renderCalculator()}
                  </div>
                </div>
              </div>
            </section>

            {/* 3.5 The Hamedia Edge Section */}
            <section id="operations" className={cn("py-20 transition-colors duration-500", 
              theme === "oasis" ? "bg-[#121214] text-white" : "bg-[#FAF7F2] text-slate-800"
            )}>
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
                  <div className="lg:col-span-6 text-left">
                    <span className={cn("font-sans text-xs font-bold tracking-widest uppercase block mb-3", t.subTitleClass)}>The Hamedia Edge</span>
                    <h2 className={cn("text-3xl sm:text-4xl leading-tight transition-all duration-500 mb-6", t.headingFont, t.textCharcoal)}>
                      AI-Enhanced Operations Engine
                    </h2>
                    <p className={cn("font-sans text-sm leading-relaxed mb-6 transition-all duration-500", t.textGray)}>
                      Our investments succeed because we don't just supply capital—we supply complete, remote operational infrastructure. Every asset in our portfolio is optimized by Hamedia Agency's 24/7 remote experts and proprietary GrowthPilot AI software.
                    </p>
                    <div className="space-y-4 font-sans">
                      <div className="flex gap-4 items-start">
                        <div className={cn("w-10 h-10 flex items-center justify-center flex-shrink-0 rounded-lg transition-all duration-500", t.iconContainer)}>
                          <Bot className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>AI-Driven Efficiencies</h4>
                          <p className={cn("text-xs leading-relaxed transition-all duration-500", t.textGray)}>Automated supply tracking, resource allocation, and predictive feed forecasting reduce waste by 40%.</p>
                        </div>
                      </div>
                      <div className="flex gap-4 items-start">
                        <div className={cn("w-10 h-10 flex items-center justify-center flex-shrink-0 rounded-lg transition-all duration-500", t.iconContainer)}>
                          <Users className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>24/7 Human Dispatch & Support</h4>
                          <p className={cn("text-xs leading-relaxed transition-all duration-500", t.textGray)}>Remote staffing teams handle dispatch routing, security monitoring, bookkeeping, and customer support around the clock.</p>
                        </div>
                      </div>
                      <div className="flex gap-4 items-start">
                        <div className={cn("w-10 h-10 flex items-center justify-center flex-shrink-0 rounded-lg transition-all duration-500", t.iconContainer)}>
                          <ShieldCheck className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>Direct Inspection & Audit</h4>
                          <p className={cn("text-xs leading-relaxed transition-all duration-500", t.textGray)}>All animal health tags, milk scales, and transport trackers report directly to our cloud ledger, ensuring complete transparency.</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="lg:col-span-6 relative">
                    <div className={cn("p-8 border transition-all duration-500", t.cardClass)}>
                      <h3 className={cn("text-xl font-bold mb-6 font-serif transition-colors duration-500", t.textCharcoal)}>Hamedia Active Operations</h3>
                      <div className="grid grid-cols-2 gap-4 text-center font-sans">
                        <div className="p-4 bg-slate-50 dark:bg-white/5 rounded-lg border border-slate-100 dark:border-white/5">
                          <span className="block text-xl font-black text-[#10a5b2] mb-1">98%</span>
                          <span className="text-[10px] uppercase font-bold text-slate-500 dark:text-gray-400">Task Accuracy</span>
                        </div>
                        <div className="p-4 bg-slate-50 dark:bg-white/5 rounded-lg border border-slate-100 dark:border-white/5">
                          <span className="block text-xl font-black text-[#e9595e] mb-1">24/7</span>
                          <span className="text-[10px] uppercase font-bold text-slate-500 dark:text-gray-400">Live Support</span>
                        </div>
                        <div className="p-4 bg-slate-50 dark:bg-white/5 rounded-lg border border-slate-100 dark:border-white/5">
                          <span className="block text-xl font-black text-[#f2b03d] mb-1">-60%</span>
                          <span className="text-[10px] uppercase font-bold text-slate-500 dark:text-gray-400">Operating Costs</span>
                        </div>
                        <div className="p-4 bg-slate-50 dark:bg-white/5 rounded-lg border border-slate-100 dark:border-white/5">
                          <span className={cn("block text-xl font-black mb-1", t.textCharcoal)}>500+</span>
                          <span className="text-[10px] uppercase font-bold text-slate-500 dark:text-gray-400">Staff Deployed</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* 4. Future Ventures Section */}
            <section id="ventures" className={cn("py-20 border-t border-b border-brand-charcoal/5 transition-colors duration-500",
              theme === "royal" ? "bg-slate-100" : theme === "oasis" ? "bg-[#161618] border-white/5" : "bg-brand-cream-revamp/10"
            )}>
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="max-w-3xl mb-16">
                  <span className={cn("font-sans text-xs font-bold tracking-widest uppercase block mb-3", t.subTitleClass)}>Ventures Pipeline</span>
                  <h2 className={cn("text-2xl sm:text-3xl lg:text-4xl leading-tight transition-all duration-500", t.headingFont, t.textCharcoal)}>
                    Investment Portfolios & Sectors
                  </h2>
                  <p className={cn("mt-4 font-sans text-sm leading-relaxed transition-all duration-500", t.textGray)}>
                    Hamedia Investments builds physical assets across four key sectors, leveraging Hamedia's AI-enhanced operations and remote teams to maximize yield.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                  {/* Vertical 1 */}
                  <div className={cn("p-6 flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                    <div>
                      <div className={cn("w-12 h-12 flex items-center justify-center mb-5", t.iconContainer)}>
                        <Wheat className="w-6 h-6" />
                      </div>
                      <h3 className={cn("text-lg font-bold mb-3 font-serif", t.textCharcoal)}>Agri-Tech & Food Systems</h3>
                      <p className={cn("font-sans text-xs leading-relaxed mb-4", t.textGray)}>
                        Deploys AI-enhanced order management, real-time crop/livestock tracking, and automated inventory systems.
                      </p>
                      <div className="text-[10px] font-sans opacity-70 mb-6">
                        <strong>Assets:</strong> Dairy herds, milking systems, and hydroponic fodder loops.
                      </div>
                    </div>
                    <span className={cn("font-sans text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded self-start", 
                      theme === "royal" ? "text-[#10a5b2] bg-[#10a5b2]/10" : theme === "oasis" ? "text-[#f2b03d] bg-[#f2b03d]/10" : "text-[#e9595e] bg-[#e9595e]/10"
                    )}>Active Portfolio</span>
                  </div>

                  {/* Vertical 2 */}
                  <div className={cn("p-6 flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                    <div>
                      <div className={cn("w-12 h-12 flex items-center justify-center mb-5", t.iconContainer)}>
                        <Truck className="w-6 h-6" />
                      </div>
                      <h3 className={cn("text-lg font-bold mb-3 font-serif", t.textCharcoal)}>Logistics & Infrastructure</h3>
                      <p className={cn("font-sans text-xs leading-relaxed mb-4", t.textGray)}>
                        Integrates AI route optimization, dispatch, and energy distribution analytics to secure cold-chains.
                      </p>
                      <div className="text-[10px] font-sans opacity-70 mb-6">
                        <strong>Assets:</strong> Solar grids, battery farms, and refrigerated transport centers.
                      </div>
                    </div>
                    <span className={cn("font-sans text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded self-start", 
                      theme === "royal" ? "text-[#10a5b2] bg-[#10a5b2]/10" : theme === "oasis" ? "text-[#f2b03d] bg-[#f2b03d]/10" : "text-[#e9595e] bg-[#e9595e]/10"
                    )}>Feasibility</span>
                  </div>

                  {/* Vertical 3 */}
                  <div className={cn("p-6 flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                    <div>
                      <div className={cn("w-12 h-12 flex items-center justify-center mb-5", t.iconContainer)}>
                        <HomeIcon className="w-6 h-6" />
                      </div>
                      <h3 className={cn("text-lg font-bold mb-3 font-serif", t.textCharcoal)}>Smart Facility Management</h3>
                      <p className={cn("font-sans text-xs leading-relaxed mb-4", t.textGray)}>
                        Coordinates AI construction scheduling, listings databases, safety auditing, and smart surveillance.
                      </p>
                      <div className="text-[10px] font-sans opacity-70 mb-6">
                        <strong>Assets:</strong> Commercial real estate, smart warehouses, and facility networks.
                      </div>
                    </div>
                    <span className={cn("font-sans text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded self-start", 
                      theme === "royal" ? "text-[#10a5b2] bg-[#10a5b2]/10" : theme === "oasis" ? "text-[#f2b03d] bg-[#f2b03d]/10" : "text-[#e9595e] bg-[#e9595e]/10"
                    )}>In Development</span>
                  </div>

                  {/* Vertical 4 */}
                  <div className={cn("p-6 flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                    <div>
                      <div className={cn("w-12 h-12 flex items-center justify-center mb-5", t.iconContainer)}>
                        <Cpu className="w-6 h-6" />
                      </div>
                      <h3 className={cn("text-lg font-bold mb-3 font-serif", t.textCharcoal)}>Digital Systems & Ops</h3>
                      <p className={cn("font-sans text-xs leading-relaxed mb-4", t.textGray)}>
                        Handles 24/7 technical support help desks, AI model deployment, and back-office accounting audits.
                      </p>
                      <div className="text-[10px] font-sans opacity-70 mb-6">
                        <strong>Assets:</strong> Data centers, processing server hardware stacks, and cloud nodes.
                      </div>
                    </div>
                    <span className={cn("font-sans text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded self-start", 
                      theme === "royal" ? "text-[#10a5b2] bg-[#10a5b2]/10" : theme === "oasis" ? "text-[#f2b03d] bg-[#f2b03d]/10" : "text-[#e9595e] bg-[#e9595e]/10"
                    )}>Planning</span>
                  </div>
                </div>
              </div>
            </section>

            {/* 5. Roadmap Model Section */}
            <section id="model" className="py-20 bg-white">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center max-w-3xl mx-auto mb-16">
                  <span className={cn("font-sans text-xs font-bold tracking-widest uppercase block mb-3", t.subTitleClass)}>Operational Roadmap</span>
                  <h2 className={cn("text-3xl font-black leading-tight transition-colors duration-500", t.headingFont, t.textCharcoal)}>
                    The Hamedia Allocation Model
                  </h2>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-4 gap-8 relative">
                  <div className="hidden md:block absolute top-[40px] left-[15%] right-[15%] h-0.5 bg-brand-light-gray" />
                  {[
                    { num: 1, title: "Platform Setup", text: "Founders construct baseline infrastructure and facilities out of pocket." },
                    { num: 2, title: "Asset Expansion", text: "Outside investors fund active, revenue-producing inventory and assets." },
                    { num: 3, title: "Operations", text: "Hamedia Agency runs operations: remote staffing, dispatch, and bookkeeping." },
                    { num: 4, title: "Yield", text: "Quarterly distributions are disbursed directly to certificate holders." }
                  ].map((step, sIdx) => (
                    <div key={sIdx} className="flex flex-col items-center text-center relative z-10">
                      <div className={cn("w-16 h-16 border-2 flex items-center justify-center font-serif text-lg font-black mb-4 shadow-sm transition-all duration-500",
                        theme === "royal" ? "bg-white border-slate-300 rounded-md text-brand-navy" : 
                        theme === "oasis" ? "bg-[#F5EFEB] border-brand-oasis-gold/40 rounded-full text-brand-oasis-gold" : 
                        "bg-brand-cream border-brand-light-gray rounded-full text-brand-charcoal"
                      )}>
                        {step.num}
                      </div>
                      <h3 className={cn("font-serif text-sm font-bold mb-2", t.textCharcoal)}>{step.title}</h3>
                      <p className={cn("font-sans text-xs leading-relaxed px-4", t.textGray)}>{step.text}</p>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* 6. FAQ Section */}
            <section className={cn("py-20 border-t border-b border-brand-charcoal/5 transition-colors duration-500",
              theme === "royal" ? "bg-slate-100" : theme === "oasis" ? "bg-[#FAF6EE] border-[#D4A218]/20" : "bg-brand-cream"
            )}>
              <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center mb-12">
                  <HelpCircle className="w-8 h-8 text-brand-blue mx-auto mb-3" />
                  <h2 className={cn("font-serif text-2xl sm:text-3xl font-black transition-colors duration-500",
                    theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal"
                  )}>Frequently Asked Questions</h2>
                </div>
                <div className="space-y-4">
                  {faqs.map((faq, idx) => (
                    <div key={idx} className={cn("overflow-hidden transition-all duration-500", t.faqClass)}>
                      <button
                        onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                        className={cn("w-full flex items-center justify-between p-5 text-left font-serif text-sm font-bold transition-colors duration-200",
                          theme === "oasis" ? "text-[#4E3E2F] hover:text-[#D4A218]" : "text-brand-charcoal hover:text-brand-red"
                        )}
                      >
                        <span>{faq.question}</span>
                        <ChevronDown className={cn("w-4 h-4 text-brand-gray transition-transform", openFaq === idx && "transform rotate-180 text-brand-red")} />
                      </button>
                      <AnimatePresence initial={false}>
                        {openFaq === idx && (
                          <motion.div
                            initial={{ height: 0 }}
                            animate={{ height: "auto" }}
                            exit={{ height: 0 }}
                            className="overflow-hidden"
                          >
                            <div className={cn("p-5 pt-0 border-t border-brand-charcoal/5 font-sans text-xs leading-relaxed",
                              theme === "oasis" ? "text-[#4E3E2F]/80" : "text-brand-gray"
                            )}>{faq.answer}</div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* 7. Contact Section */}
            <section id="contact" className="py-20 bg-white">
              <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <div className="text-center max-w-2xl mx-auto mb-12">
                  <span className={cn("font-sans text-xs font-bold tracking-widest uppercase block mb-3", t.subTitleClass)}>Join Our Network</span>
                  <h2 className={cn("text-3xl font-black leading-tight transition-all duration-500", t.headingFont, t.textCharcoal)}>
                    Investor Relations Inquiry
                  </h2>
                  <p className={cn("mt-4 font-sans text-xs sm:text-sm leading-relaxed transition-all duration-500", t.textGray)}>
                    If you are interested in passive, asset-backed economic participation, please submit an inquiry form below.
                  </p>
                </div>
                {renderContactForm()}
              </div>
            </section>
          </motion.div>
        )}

        {/* ============================================================
            STRUCTURE 2: INTERACTIVE SPLIT SLIDE DECK
            ============================================================ */}
        {structure === "structure2" && (
          <motion.div
            key="structure2"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"
          >
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              
              {/* Left Column: Static Outline Pitch / Navigation */}
              <div className={cn("lg:col-span-4 lg:sticky lg:top-[160px] p-6 border transition-all duration-500 z-10", t.slideLeftPanelBg)}>
                <div className="flex items-center gap-2 mb-4">
                  <HamediaLogo variant="icon" iconClassName="w-10 h-10" />
                  <div>
                    <h3 className={cn("font-serif text-sm font-black uppercase leading-none", theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal")}>Hamedia</h3>
                    <span className={cn("font-sans text-[8px] tracking-[0.1em] font-bold", theme === "oasis" ? "text-[#D4A218]" : "text-brand-gray")}>PITCH OVERVIEW</span>
                  </div>
                </div>

                <div className={cn("h-px my-4", theme === "oasis" ? "bg-[#D4A218]/20" : "bg-brand-charcoal/10")} />

                <h2 className={cn("text-base font-bold mb-3 font-serif", theme === "oasis" ? "text-[#4E3E2F]" : "text-brand-charcoal")}>
                  Investment Memorandum
                </h2>
                <p className={cn("font-sans text-xs leading-relaxed mb-6", theme === "oasis" ? "text-[#4E3E2F]/80" : "text-brand-gray")}>
                  Scroll through our dynamic slides on the right to examine our economic models, asset profiles, and upcoming venture roadmap.
                </p>

                {/* Slides Nav Map */}
                <div className="space-y-2 font-sans text-xs">
                  <a href="#slide-thesis" className={cn("flex items-center gap-2 py-2 px-3 rounded transition-colors font-bold",
                    theme === "oasis" ? "bg-[#D4A218]/10 hover:bg-[#D4A218]/20 text-[#4E3E2F] hover:text-[#D4A218]" : "bg-brand-charcoal/5 hover:bg-brand-charcoal/10 text-brand-charcoal hover:text-brand-red"
                  )}>
                    <BookOpen className="w-3.5 h-3.5" /> 1. The Executive Thesis
                  </a>
                  <a href="#slide-flagship" className={cn("flex items-center gap-2 py-2 px-3 rounded transition-colors font-bold",
                    theme === "oasis" ? "bg-[#D4A218]/10 hover:bg-[#D4A218]/20 text-[#4E3E2F] hover:text-[#D4A218]" : "bg-brand-charcoal/5 hover:bg-brand-charcoal/10 text-brand-charcoal hover:text-brand-red"
                  )}>
                    <Award className="w-3.5 h-3.5" /> 2. Arghandab Dairy Farm
                  </a>
                  <a href="#slide-ops" className={cn("flex items-center gap-2 py-2 px-3 rounded transition-colors font-bold",
                    theme === "oasis" ? "bg-[#D4A218]/10 hover:bg-[#D4A218]/20 text-[#4E3E2F] hover:text-[#D4A218]" : "bg-brand-charcoal/5 hover:bg-brand-charcoal/10 text-brand-charcoal hover:text-brand-red"
                  )}>
                    <Bot className="w-3.5 h-3.5" /> 3. The Hamedia Edge
                  </a>
                  <a href="#slide-calc" className={cn("flex items-center gap-2 py-2 px-3 rounded transition-colors font-bold",
                    theme === "oasis" ? "bg-[#D4A218]/10 hover:bg-[#D4A218]/20 text-[#4E3E2F] hover:text-[#D4A218]" : "bg-brand-charcoal/5 hover:bg-brand-charcoal/10 text-brand-charcoal hover:text-brand-red"
                  )}>
                    <Calculator className="w-3.5 h-3.5" /> 4. Herd Simulator Widget
                  </a>
                  <a href="#slide-pipeline" className={cn("flex items-center gap-2 py-2 px-3 rounded transition-colors font-bold",
                    theme === "oasis" ? "bg-[#D4A218]/10 hover:bg-[#D4A218]/20 text-[#4E3E2F] hover:text-[#D4A218]" : "bg-brand-charcoal/5 hover:bg-brand-charcoal/10 text-brand-charcoal hover:text-brand-red"
                  )}>
                    <Layers className="w-3.5 h-3.5" /> 5. Investment Verticals
                  </a>
                  <a href="#slide-inquire" className={cn("flex items-center gap-2 py-2 px-3 rounded transition-colors font-bold",
                    theme === "oasis" ? "bg-[#D4A218]/10 hover:bg-[#D4A218]/20 text-[#4E3E2F] hover:text-[#D4A218]" : "bg-brand-charcoal/5 hover:bg-brand-charcoal/10 text-brand-charcoal hover:text-brand-red"
                  )}>
                    <Send className="w-3.5 h-3.5" /> 6. Investor Registration
                  </a>
                </div>

                <div className={cn("mt-8 pt-4 border-t font-sans text-[10px] leading-relaxed flex flex-col gap-2",
                  theme === "oasis" ? "border-[#D4A218]/20 text-[#4E3E2F]/60" : "border-brand-charcoal/5 text-brand-gray/60"
                )}>
                  <span className="flex items-center gap-1.5"><Phone className="w-3 h-3" /> +1-949-299-6263</span>
                  <span className="flex items-center gap-1.5"><Mail className="w-3 h-3" /> info@hamediainvestment.com</span>
                </div>
              </div>

              {/* Right Column: Slides Feed */}
              <div className="lg:col-span-8 space-y-12">
                
                {/* Slide 1: Executive Thesis */}
                <div id="slide-thesis" className={cn("p-8 border transition-all duration-500", t.cardClass)}>
                  <span className={cn("font-sans text-[9px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>Slide 01 // Overview</span>
                  <h3 className={cn("text-xl sm:text-2xl font-black mb-4 transition-colors duration-500", t.headingFont, t.textCharcoal)}>
                    Asset-Backed Economic Independence
                  </h3>
                  <div className={cn("w-16 h-0.5 mb-4 transition-all duration-500", t.dividerClass)} />
                  <p className={cn("font-sans text-xs sm:text-sm leading-relaxed mb-4 transition-all duration-500", t.textGray)}>
                    Hamedia Investments is focused on developing and investing in multiple real-asset projects across Afghanistan. We deploy capital directly into productive sectors (livestock, infrastructure, and energy) to build economic self-sufficiency, secured entirely by physical inventory.
                  </p>
                  <p className={cn("font-sans text-xs sm:text-sm leading-relaxed mb-6 transition-all duration-500", t.textGray)}>
                    Our founders carry the core infrastructure risk (purchasing agricultural land, constructing facilities) so that investor proceeds buy only active, income-producing assets (such as the dairy herd lines in our flagship Arghandab project).
                  </p>
                  <div className="grid grid-cols-2 gap-4 text-center mt-6">
                    <div className="bg-brand-charcoal/5 p-4 rounded">
                      <span className="block font-serif text-lg font-black text-brand-blue">100%</span>
                      <span className="font-sans text-[9px] text-brand-gray uppercase">Founder Land Equity</span>
                    </div>
                    <div className="bg-brand-charcoal/5 p-4 rounded">
                      <span className="block font-serif text-lg font-black text-brand-red">Zero</span>
                      <span className="font-sans text-[9px] text-brand-gray uppercase">Investor Infrastructure Debt</span>
                    </div>
                  </div>
                </div>

                {/* Slide 2: Arghandab Dairy Farm */}
                <div id="slide-flagship" className={cn("p-8 border transition-all duration-500", t.cardClass)}>
                  <span className={cn("font-sans text-[9px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>Slide 02 // Flagship</span>
                  <h3 className={cn("text-xl sm:text-2xl font-black mb-4 transition-colors duration-500", t.headingFont, t.textCharcoal)}>
                    Arghandab Dairy Farm: Kandahar
                  </h3>
                  <div className="w-16 h-0.5 bg-brand-blue mb-4" />
                  <p className={cn("font-sans text-xs sm:text-sm leading-relaxed mb-4 transition-all duration-500", t.textGray)}>
                    Our first project is an operating dairy farm in Kandahar, utilizing a closed-loop fodder system to secure feed supply at fixed internal pricing.
                  </p>
                  <p className={cn("font-sans text-xs sm:text-sm leading-relaxed mb-6 transition-all duration-500", t.textGray)}>
                    Under the <strong>Economic Participation Certificate</strong>, investors fund herd inventory expansion and acquire a 33% interest in the milk production cash yield, offspring valuations, and livestock exit valuations.
                  </p>
                  <div className="space-y-2.5 font-sans text-xs text-brand-gray bg-brand-charcoal/5 p-4 rounded">
                    <div className="flex gap-2 items-center"><CheckCircle className="w-4 h-4 text-brand-red" /> 33% Net Milk Yield Distributions</div>
                    <div className="flex gap-2 items-center"><CheckCircle className="w-4 h-4 text-brand-red" /> 33% realized payout from male calves</div>
                    <div className="flex gap-2 items-center"><CheckCircle className="w-4 h-4 text-brand-red" /> 33% livestock market value exit buyout</div>
                  </div>
                </div>

                {/* Slide 3: The Hamedia Edge (Operations) */}
                <div id="slide-ops" className={cn("p-8 border transition-all duration-500", t.cardClass)}>
                  <span className={cn("font-sans text-[9px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>Slide 03 // Operations</span>
                  <h3 className={cn("text-xl sm:text-2xl font-black mb-4 transition-colors duration-500", t.headingFont, t.textCharcoal)}>
                    The Hamedia Edge
                  </h3>
                  <div className={cn("w-16 h-0.5 mb-6 transition-all duration-500", t.dividerClass)} />
                  <p className={cn("font-sans text-xs sm:text-sm leading-relaxed mb-6 transition-all duration-500", t.textGray)}>
                    Every asset is optimized by Hamedia Agency's 24/7 remote staffing, reducing operating overhead by up to 60%.
                  </p>
                  <div className="space-y-4 font-sans text-xs">
                    <div className="flex gap-3">
                      <Bot className={cn("w-5 h-5 flex-shrink-0 mt-0.5", t.checkIcon)} />
                      <div>
                        <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>AI-Driven Efficiency</h4>
                        <p className={cn("font-sans text-[11px] leading-relaxed transition-all duration-500", t.textGray)}>Hydroponic feed analytics and cattle tracking reduce biological waste by 40%.</p>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <Users className={cn("w-5 h-5 flex-shrink-0 mt-0.5", t.checkIcon)} />
                      <div>
                        <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>24/7 Remote Teams</h4>
                        <p className={cn("font-sans text-[10px] leading-relaxed transition-all duration-500", t.textGray)}>Handles bookkeeping, security monitoring, dispatch routing, and sales.</p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Slide 4: Calculator Widget */}
                <div id="slide-calc" className="w-full">
                  {renderCalculator()}
                </div>

                {/* Slide 5: Pipeline Pipelines */}
                <div id="slide-pipeline" className={cn("p-8 border transition-all duration-500", t.cardClass)}>
                  <span className={cn("font-sans text-[9px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>Slide 05 // Ventures</span>
                  <h3 className={cn("text-xl sm:text-2xl font-black mb-4 transition-colors duration-500", t.headingFont, t.textCharcoal)}>
                    Investment Verticals
                  </h3>
                  <div className={cn("w-16 h-0.5 mb-6 transition-all duration-500", t.dividerClass)} />
                  <div className="space-y-4">
                    <div className="flex gap-4">
                      <div className={cn("w-10 h-10 flex items-center justify-center flex-shrink-0 transition-all duration-500", t.iconContainer)}>
                        <Wheat className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>Agri-Tech & Food Systems</h4>
                        <p className={cn("font-sans text-xs leading-relaxed transition-all duration-500", t.textGray)}>AI order management, crop tracking, cattle tags, and hydroponic loops.</p>
                      </div>
                    </div>
                    <div className="flex gap-4">
                      <div className={cn("w-10 h-10 flex items-center justify-center flex-shrink-0 transition-all duration-500", t.iconContainer)}>
                        <Truck className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>Logistics & Infrastructure</h4>
                        <p className={cn("font-sans text-xs leading-relaxed transition-all duration-500", t.textGray)}>AI route optimization, fleet dispatch, solar grids, and cold storage hubs.</p>
                      </div>
                    </div>
                    <div className="flex gap-4">
                      <div className={cn("w-10 h-10 flex items-center justify-center flex-shrink-0 transition-all duration-500", t.iconContainer)}>
                        <HomeIcon className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>Smart Facility Management</h4>
                        <p className={cn("font-sans text-xs leading-relaxed transition-all duration-500", t.textGray)}>AI construction scheduling, listings data, safety audits, and surveillance.</p>
                      </div>
                    </div>
                    <div className="flex gap-4">
                      <div className={cn("w-10 h-10 flex items-center justify-center flex-shrink-0 transition-all duration-500", t.iconContainer)}>
                        <Cpu className="w-5 h-5" />
                      </div>
                      <div>
                        <h4 className={cn("font-serif text-sm font-bold mb-1 transition-colors duration-500", t.textCharcoal)}>Digital Systems & Operations</h4>
                        <p className={cn("font-sans text-xs leading-relaxed transition-all duration-500", t.textGray)}>24/7 technical help desks, AI model deployment, and back-office accounting.</p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Slide 5: Inquiry form */}
                <div id="slide-inquire" className="w-full">
                  {renderContactForm()}
                </div>

              </div>
            </div>
          </motion.div>
        )}

        {/* ============================================================
            STRUCTURE 3: BENTO GRID DASHBOARD
            ============================================================ */}
        {structure === "structure3" && (
          <motion.div
            key="structure3"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"
          >
            {/* Bento Grid layout */}
            <div className="grid grid-cols-1 md:grid-cols-6 gap-6 auto-rows-auto">
              
              {/* Block A: Brand Thesis (Large - spans 4 cols md) */}
              <div className={cn("md:col-span-4 p-8 border flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                <div>
                  <div className="flex items-center gap-3 mb-6">
                    <HamediaLogo variant="icon" iconClassName="w-12 h-12" />
                    <div>
                      <h2 className={cn("text-lg font-black tracking-widest uppercase transition-colors duration-500", t.textCharcoal)}>
                        HAMEDIA INVESTMENTS
                      </h2>
                      <span className="font-sans text-[8px] text-brand-red font-bold uppercase tracking-widest block">AFGHANISTAN PORTFOLIO</span>
                    </div>
                  </div>
                  <h3 className={cn("text-xl sm:text-2xl font-black mb-4 leading-tight transition-colors duration-500", t.headingFont, t.textCharcoal)}>
                    Deploying Capital Directly into Productive Real Assets
                  </h3>
                  <p className={cn("font-sans text-xs sm:text-sm leading-relaxed transition-colors duration-500", t.textGray)}>
                    Hamedia Investments structures passive economic participation across multiple development projects. We acquire and build physical assets—starting with the flagship Arghandab Dairy Farm—to deliver sustainable yields managed entirely by Hamedia Agency's operations.
                  </p>
                </div>
                <div className="grid grid-cols-3 gap-4 border-t border-brand-charcoal/5 pt-6 mt-8 text-center font-serif text-xs">
                  <div>
                    <span className="block font-black text-brand-blue text-sm sm:text-base">01</span>
                    <span className="font-sans text-[8px] text-brand-gray uppercase">Active Farm</span>
                  </div>
                  <div>
                    <span className="block font-black text-brand-red text-sm sm:text-base">33%</span>
                    <span className="font-sans text-[8px] text-brand-gray uppercase">Investor Share</span>
                  </div>
                  <div>
                    <span className="block font-black text-brand-gold-dark text-sm sm:text-base">Solar</span>
                    <span className="font-sans text-[8px] text-brand-gray uppercase">Fodder Loops</span>
                  </div>
                </div>
              </div>

              {/* Block B: Flagship Details (Medium - spans 2 cols md) */}
              <div className={cn("md:col-span-2 p-6 border flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                <div>
                  <span className={cn("font-sans text-[8px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>FLAGSHIP VENTURE</span>
                  <h3 className={cn("text-lg font-bold mb-3 font-serif transition-colors duration-500", t.textCharcoal)}>
                    Arghandab Dairy Farm
                  </h3>
                  <div className="w-10 h-0.5 bg-brand-blue mb-4" />
                  <p className={cn("font-sans text-xs leading-relaxed mb-4 transition-colors duration-500", t.textGray)}>
                    Located in Kandahar. Built with a closed fodder supply cycle to reduce operating costs. Capital buys livestock inventory; investors bypass platform setup risk.
                  </p>
                </div>
                <div className="space-y-2 bg-brand-charcoal/5 p-3.5 rounded text-[10px] font-sans text-brand-gray leading-relaxed">
                  <span className={cn("block font-bold mb-1 uppercase tracking-wider text-[8px]", t.textCharcoal)}>Economic Certificate:</span>
                  <div className="flex gap-2 items-center"><CheckCircle className={cn("w-3.5 h-3.5 flex-shrink-0", t.checkIcon)} /> 33% Milk Operations Yield</div>
                  <div className="flex gap-2 items-center"><CheckCircle className={cn("w-3.5 h-3.5 flex-shrink-0", t.checkIcon)} /> 33% Male Offspring Payout</div>
                  <div className="flex gap-2 items-center"><CheckCircle className={cn("w-3.5 h-3.5 flex-shrink-0", t.checkIcon)} /> 33% Herd exit value buyout</div>
                </div>
              </div>

              {/* Block C: Simulator Widget (Large - spans 4 cols md) */}
              <div className="md:col-span-4">
                {renderCalculator()}
              </div>

              {/* Block D: Future Pipelines (Medium - spans 2 cols md) */}
              <div className={cn("md:col-span-2 p-6 border flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                <div>
                  <span className={cn("font-sans text-[8px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>DEVELOPMENT PIPELINE</span>
                  <h3 className={cn("text-lg font-bold mb-4 font-serif transition-colors duration-500", t.textCharcoal)}>
                    Investment Verticals
                  </h3>
                  <div className="space-y-3.5">
                    <div className="flex gap-3">
                      <Wheat className={cn("w-5 h-5 flex-shrink-0", t.checkIcon)} />
                      <div>
                        <h4 className={cn("font-serif text-[11px] font-bold leading-tight transition-colors duration-500", t.textCharcoal)}>Agri-Tech & Food Systems</h4>
                        <p className={cn("font-sans text-[9px] leading-tight transition-all duration-500", t.textGray)}>AI crop tracking, cattle tags, and fodder loops.</p>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <Truck className={cn("w-5 h-5 flex-shrink-0", t.checkIcon)} />
                      <div>
                        <h4 className={cn("font-serif text-[11px] font-bold leading-tight transition-colors duration-500", t.textCharcoal)}>Logistics & Infrastructure</h4>
                        <p className={cn("font-sans text-[9px] leading-tight transition-all duration-500", t.textGray)}>Route optimization, solar grids, and cold chains.</p>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <HomeIcon className={cn("w-5 h-5 flex-shrink-0", t.checkIcon)} />
                      <div>
                        <h4 className={cn("font-serif text-[11px] font-bold leading-tight transition-colors duration-500", t.textCharcoal)}>Smart Facility Management</h4>
                        <p className={cn("font-sans text-[9px] leading-tight transition-all duration-500", t.textGray)}>AI construction scheduling, safety audits, and camera loops.</p>
                      </div>
                    </div>
                    <div className="flex gap-3">
                      <Cpu className={cn("w-5 h-5 flex-shrink-0", t.checkIcon)} />
                      <div>
                        <h4 className={cn("font-serif text-[11px] font-bold leading-tight transition-colors duration-500", t.textCharcoal)}>Digital Systems & Operations</h4>
                        <p className={cn("font-sans text-[9px] leading-tight transition-all duration-500", t.textGray)}>24/7 technical help desks, AI models, and accounting.</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="h-0.5" />
              </div>

              {/* Block E: Security & Backing (Medium - spans 3 cols md) */}
              <div className={cn("md:col-span-3 p-6 border flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                <div>
                  <span className={cn("font-sans text-[8px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>BACKING & PROTECTION</span>
                  <h3 className={cn("text-base font-bold mb-3 font-serif transition-colors duration-500", t.textCharcoal)}>
                    Security Framework
                  </h3>
                  <p className={cn("font-sans text-[11px] leading-relaxed transition-all duration-500", t.textGray)}>
                    Founder backing eliminates infrastructural risk. Color-coded ear tags secure livestock tracking. Inspection rights are guaranteed inside the Economic Participation Certificate.
                  </p>
                </div>
                <div className="flex items-center gap-2 text-xs font-serif font-black text-brand-blue mt-4">
                  <ShieldCheck className={cn("w-5 h-5 flex-shrink-0", t.checkIcon)} />
                  <span className={cn("transition-colors duration-500", t.textCharcoal)}>100% Contract Backed</span>
                </div>
              </div>

              {/* Block I: AI-Enhanced Operations (Medium - spans 3 cols md) */}
              <div className={cn("md:col-span-3 p-6 border flex flex-col justify-between transition-all duration-500", t.cardClass)}>
                <div>
                  <span className={cn("font-sans text-[8px] font-bold tracking-widest uppercase block mb-2", t.subTitleClass)}>OPERATIONAL INFRASTRUCTURE</span>
                  <h3 className={cn("text-base font-bold mb-3 font-serif transition-colors duration-500", t.textCharcoal)}>
                    The Hamedia Edge
                  </h3>
                  <p className={cn("font-sans text-[11px] leading-relaxed transition-all duration-500", t.textGray)}>
                    We deploy Hamedia Agency's 24/7 human staffing and GrowthPilot AI tools to manage inventory, forecast supply cycles, and audit physical accounts automatically.
                  </p>
                </div>
                <div className="flex items-center gap-2 text-xs font-serif font-black mt-4">
                  <Bot className={cn("w-5 h-5 flex-shrink-0", t.checkIcon)} />
                  <span className={cn("transition-colors duration-500", t.textCharcoal)}>24/7 Remote-Managed Assets</span>
                </div>
              </div>

              {/* Block F: Form Widget (Large - spans 6 cols md) */}
              <div className="md:col-span-6">
                {renderContactForm()}
              </div>

            </div>
          </motion.div>
        )}

      </AnimatePresence>
    </div>
  );
}
